In [70]:
import pandas as pd
import matplotlib.pyplot as plt

## Leitura de um dataset novo

In [71]:
df = pd.read_csv('dataset_tennis.csv')

In [72]:
df

,player_id,player_slug,first_name,last_name,player_url,flag_code,residence,birthplace,birthdate,birth_year,birth_month,birth_day,turned_pro,weight_lbs,weight_kg,height_ft,height_inches,height_cm,handedness,backhand
0,a002,ricardo-acuna,Ricardo,Acuna,http://www.atpworldtour.com/en/players/ricardo...,CHI,"Jupiter, FL, USA","Santiago, Chile",1958.01.13,1958.0,1.0,13.0,0.0,150.0,68.0,"5'9""",69.0,175.0,NaN,NaN
1,a001,sadiq-abdullahi,Sadiq,Abdullahi,http://www.atpworldtour.com/en/players/sadiq-a...,NGR,NaN,NaN,1960.02.02,1960.0,2.0,2.0,0.0,0.0,0.0,"0'0""",0.0,0.0,NaN,NaN
2,a005,nelson-aerts,Nelson,Aerts,http://www.atpworldtour.com/en/players/nelson-...,BRA,NaN,"Cachoeira Do Sul, Brazil",1963.04.25,1963.0,4.0,25.0,0.0,165.0,75.0,"6'2""",74.0,188.0,NaN,NaN
3,a004,egan-adams,Egan,Adams,http://www.atpworldtour.com/en/players/egan-ad...,USA,"Palmetto, FL, USA","Miami Beach, FL, USA",1959.06.15,1959.0,6.0,15.0,0.0,160.0,73.0,"5'10""",70.0,178.0,NaN,NaN
4,a006,ronald-agenor,Ronald,Agenor,http://www.atpworldtour.com/en/players/ronald-...,USA,"Beverly Hills, California, USA","Rabat, Morocco",1964.11.13,1964.0,11.0,13.0,1983.0,180.0,82.0,"5'11""",71.0,180.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10907,z435,a-zorab,A.,Zorab,http://www.atpworldtour.com/en/players/a-zorab...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10908,z437,j-zimmermann,J.,Zimmermann,http://www.atpworldtour.com/en/players/j-zimme...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10909,z436,g-zinn,G.,Zinn,http://www.atpworldtour.com/en/players/g-zinn/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10910,z440,c-zenger,C.,Zenger,http://www.atpworldtour.com/en/players/c-zenge...,GER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10911,z442,a-ziffo,A.,Ziffo,http://www.atpworldtour.com/en/players/a-ziffo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:

df1 = pd.read_csv('switzerland_final.csv')

Criação de uma nova coluna com novo dataset

In [74]:
df['full_name'] = df['first_name'] + ' ' + df['last_name']

In [75]:
df_merged = pd.merge(df1, df[['full_name', 'birth_year','flag_code','weight_kg','turned_pro','height_cm']], left_on='Player1_Name', right_on='full_name', how='left')

In [76]:
df_merged

,Unnamed: 0,Player1_Name,Player1_Height,Tournament,Location,Ground,Prize,GameRound,Player2_Rank,Num_Sets,...,Player2_Name,Player2_Height,Player1_Rank,Rank_Diff,full_name,birth_year,flag_code,weight_kg,turned_pro,height_cm
0,0,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 16,64,2,...,Lukasz Kubot,191,1,63,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
1,1,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 32,47,3,...,Xavier Malisse,185,1,46,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
2,2,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Semi-Finals,32,2,...,Viktor Troicki,193,3,29,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
3,3,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Quarter-Finals,66,2,...,Robin Haase,191,3,63,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
4,4,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Round of 32,26,2,...,Ernests Gulbis,191,3,23,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4922,4922,Juan Manuel Benitez Chavarriaga,184,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 16,1011,2,...,Loic Perret,188,646,365,NaN,NaN,NaN,NaN,NaN,NaN
4923,4923,Marvin Moeller,178,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,Round of 32,1298,3,...,Patrik Hartmeier,184,614,684,Marvin Moeller,1999.0,GER,69.0,NaN,178.0
4924,4924,Marvin Moeller,178,Switzerland F5,"Sion, Switzerland",Clay,15000.0,Round of 32,545,3,...,Pascal Meis,180,1128,583,Marvin Moeller,1999.0,GER,69.0,NaN,178.0
4925,4925,Maxence Beauge,183,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 32,941,2,...,Issei Okamura,170,1325,384,NaN,NaN,NaN,NaN,NaN,NaN
4926,4926,Nicolas Parizzia,184,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,Round of 32,2048,3,...,Gian Luca Tanner,191,1672,376,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
df_merged = pd.merge(df1, df[['full_name', 'birth_year','flag_code','weight_kg','turned_pro','height_cm']], left_on='Player2_Name', right_on='full_name', how='left')

In [78]:
df_merged

,Unnamed: 0,Player1_Name,Player1_Height,Tournament,Location,Ground,Prize,GameRound,Player2_Rank,Num_Sets,...,Player2_Name,Player2_Height,Player1_Rank,Rank_Diff,full_name,birth_year,flag_code,weight_kg,turned_pro,height_cm
0,0,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 16,64,2,...,Lukasz Kubot,191,1,63,Lukasz Kubot,1982.0,POL,86.0,2002.0,191.0
1,1,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 32,47,3,...,Xavier Malisse,185,1,46,Xavier Malisse,1980.0,BEL,83.0,1998.0,185.0
2,2,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Semi-Finals,32,2,...,Viktor Troicki,193,3,29,Viktor Troicki,1986.0,SRB,86.0,2006.0,193.0
3,3,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Quarter-Finals,66,2,...,Robin Haase,191,3,63,Robin Haase,1987.0,NED,71.0,2005.0,191.0
4,4,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Round of 32,26,2,...,Ernests Gulbis,191,3,23,Ernests Gulbis,1988.0,LAT,88.0,2004.0,193.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,4922,Juan Manuel Benitez Chavarriaga,184,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 16,1011,2,...,Loic Perret,188,646,365,Loic Perret,1994.0,SUI,NaN,NaN,NaN
4928,4923,Marvin Moeller,178,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,Round of 32,1298,3,...,Patrik Hartmeier,184,614,684,NaN,NaN,NaN,NaN,NaN,NaN
4929,4924,Marvin Moeller,178,Switzerland F5,"Sion, Switzerland",Clay,15000.0,Round of 32,545,3,...,Pascal Meis,180,1128,583,Pascal Meis,1993.0,GER,NaN,NaN,NaN
4930,4925,Maxence Beauge,183,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 32,941,2,...,Issei Okamura,170,1325,384,NaN,NaN,NaN,NaN,NaN,NaN
4931,4926,Nicolas Parizzia,184,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,Round of 32,2048,3,...,Gian Luca Tanner,191,1672,376,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
df_merged.to_csv('jogadores_year.csv', index=False)

In [80]:
df2 = pd.read_csv('jogadores_year.csv')

In [81]:
df_merged1 = pd.merge(df2, df[['full_name', 'birth_year','flag_code','weight_kg','turned_pro','height_cm']], left_on='Player1_Name', right_on='full_name', how='left')

In [82]:
df_merged1

,Unnamed: 0,Player1_Name,Player1_Height,Tournament,Location,Ground,Prize,GameRound,Player2_Rank,Num_Sets,...,flag_code_x,weight_kg_x,turned_pro_x,height_cm_x,full_name_y,birth_year_y,flag_code_y,weight_kg_y,turned_pro_y,height_cm_y
0,0,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 16,64,2,...,POL,86.0,2002.0,191.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
1,1,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 32,47,3,...,BEL,83.0,1998.0,185.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
2,2,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Semi-Finals,32,2,...,SRB,86.0,2006.0,193.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
3,3,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Quarter-Finals,66,2,...,NED,71.0,2005.0,191.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
4,4,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Round of 32,26,2,...,LAT,88.0,2004.0,193.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,4922,Juan Manuel Benitez Chavarriaga,184,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 16,1011,2,...,SUI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4928,4923,Marvin Moeller,178,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,Round of 32,1298,3,...,NaN,NaN,NaN,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,178.0
4929,4924,Marvin Moeller,178,Switzerland F5,"Sion, Switzerland",Clay,15000.0,Round of 32,545,3,...,GER,NaN,NaN,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,178.0
4930,4925,Maxence Beauge,183,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 32,941,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4931,4926,Nicolas Parizzia,184,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,Round of 32,2048,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
df_merged1['Start_Date']

0       2011-10-31
1       2011-10-31
2       2010-11-01
3       2010-11-01
4       2010-11-01
           ...
4927    2017-08-14
4928    2021-03-08
4929    2017-08-28
4930    2017-08-14
4931    2021-08-23
Name: Start_Date, Length: 4932, dtype: object

In [84]:
df_merged1['Start_Date'] = pd.to_datetime(df_merged1['Start_Date'], format='%Y-%m-%d')

In [85]:
df_merged1['Start_year'] = df_merged1['Start_Date'].dt.year

In [86]:
df_merged1['Player1_age'] = df_merged1['Start_Date'].dt.year - df_merged1['birth_year_y']

In [87]:
df_merged1['Player2_age'] = df_merged1['Start_Date'].dt.year - df_merged1['birth_year_x']

In [88]:
df_merged1

,Unnamed: 0,Player1_Name,Player1_Height,Tournament,Location,Ground,Prize,GameRound,Player2_Rank,Num_Sets,...,height_cm_x,full_name_y,birth_year_y,flag_code_y,weight_kg_y,turned_pro_y,height_cm_y,Start_year,Player1_age,Player2_age
0,0,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 16,64,2,...,191.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,2011,24.0,29.0
1,1,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 32,47,3,...,185.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,2011,24.0,31.0
2,2,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Semi-Finals,32,2,...,193.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,2010,23.0,24.0
3,3,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Quarter-Finals,66,2,...,191.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,2010,23.0,23.0
4,4,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Round of 32,26,2,...,193.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,2010,23.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,4922,Juan Manuel Benitez Chavarriaga,184,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 16,1011,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,NaN,23.0
4928,4923,Marvin Moeller,178,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,Round of 32,1298,3,...,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,178.0,2021,22.0,NaN
4929,4924,Marvin Moeller,178,Switzerland F5,"Sion, Switzerland",Clay,15000.0,Round of 32,545,3,...,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,178.0,2017,18.0,24.0
4930,4925,Maxence Beauge,183,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 32,941,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,NaN,NaN
4931,4926,Nicolas Parizzia,184,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,Round of 32,2048,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN

In [89]:


# Substitua os valores 0 na coluna "Player1_height" pelos valores da coluna "height_cm_y"  # substitua os zeros por NaN
df_merged1['Player1_Height'] = df_merged1['Player1_Height'].fillna(df_merged1['height_cm_y'])

df_merged1

,Unnamed: 0,Player1_Name,Player1_Height,Tournament,Location,Ground,Prize,GameRound,Player2_Rank,Num_Sets,...,height_cm_x,full_name_y,birth_year_y,flag_code_y,weight_kg_y,turned_pro_y,height_cm_y,Start_year,Player1_age,Player2_age
0,0,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 16,64,2,...,191.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,2011,24.0,29.0
1,1,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 32,47,3,...,185.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,2011,24.0,31.0
2,2,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Semi-Finals,32,2,...,193.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,2010,23.0,24.0
3,3,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Quarter-Finals,66,2,...,191.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,2010,23.0,23.0
4,4,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Round of 32,26,2,...,193.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,2010,23.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,4922,Juan Manuel Benitez Chavarriaga,184,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 16,1011,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,NaN,23.0
4928,4923,Marvin Moeller,178,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,Round of 32,1298,3,...,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,178.0,2021,22.0,NaN
4929,4924,Marvin Moeller,178,Switzerland F5,"Sion, Switzerland",Clay,15000.0,Round of 32,545,3,...,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,178.0,2017,18.0,24.0
4930,4925,Maxence Beauge,183,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 32,941,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,NaN,NaN
4931,4926,Nicolas Parizzia,184,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,Round of 32,2048,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN

In [90]:
df_merged1['Player1_Height'].isna()

0       False
1       False
2       False
3       False
4       False
        ...
4927    False
4928    False
4929    False
4930    False
4931    False
Name: Player1_Height, Length: 4932, dtype: bool

In [91]:
# Substitua os valores NaN na coluna "Player2_height" pelos valores da coluna "height_cm_x"
df_merged1['Player2_Height'] = df_merged1['Player2_Height'].fillna(df_merged1['height_cm_x'])

df_merged1

,Unnamed: 0,Player1_Name,Player1_Height,Tournament,Location,Ground,Prize,GameRound,Player2_Rank,Num_Sets,...,height_cm_x,full_name_y,birth_year_y,flag_code_y,weight_kg_y,turned_pro_y,height_cm_y,Start_year,Player1_age,Player2_age
0,0,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 16,64,2,...,191.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,2011,24.0,29.0
1,1,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 32,47,3,...,185.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,2011,24.0,31.0
2,2,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Semi-Finals,32,2,...,193.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,2010,23.0,24.0
3,3,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Quarter-Finals,66,2,...,191.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,2010,23.0,23.0
4,4,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Round of 32,26,2,...,193.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,2010,23.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,4922,Juan Manuel Benitez Chavarriaga,184,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 16,1011,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,NaN,23.0
4928,4923,Marvin Moeller,178,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,Round of 32,1298,3,...,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,178.0,2021,22.0,NaN
4929,4924,Marvin Moeller,178,Switzerland F5,"Sion, Switzerland",Clay,15000.0,Round of 32,545,3,...,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,178.0,2017,18.0,24.0
4930,4925,Maxence Beauge,183,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 32,941,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,NaN,NaN
4931,4926,Nicolas Parizzia,184,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,Round of 32,2048,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN

In [124]:
print('Valores nulos Player1') 
df_merged1['Player1_Height'].isna().sum()

Valores nulos Player1

0

In [125]:
print('Valores nulos Player2') 
df_merged1['Player2_Height'].isna().sum()

Valores nulos Player2

0

In [126]:
df_merged1 = df_merged1.drop(['height_cm_x','height_cm_y','Unnamed: 0'],axis=1)

KeyError: "['height_cm_x', 'height_cm_y', 'Unnamed: 0'] not found in axis"

In [ ]:
df_merged1

In [ ]:
df_merged1.rename(columns={'weight_kg_y': 'Player1_Weight'}, inplace=True)
df_merged1.rename(columns={'weight_kg_x': 'Player2_Weight'}, inplace=True)

In [ ]:
df_merged1

In [127]:
df_merged1['Player1_turned_pro'] = df_merged1['Start_Date'].dt.year - df_merged1['turned_pro_y']
df_merged1['Player2_turned_pro'] = df_merged1['Start_Date'].dt.year - df_merged1['turned_pro_x']

In [97]:
df_merged1

,Player1_Name,Player1_Height,Tournament,Location,Ground,Prize,GameRound,Player2_Rank,Num_Sets,TotalPoints,...,full_name_y,birth_year_y,flag_code_y,Player1_Weight,turned_pro_y,Start_year,Player1_age,Player2_age,Player1_turned_pro,Player2_turned_pro
0,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 16,64,2,15,...,Novak Djokovic,1987.0,SRB,77.0,2003.0,2011,24.0,29.0,8.0,9.0
1,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 32,47,3,30,...,Novak Djokovic,1987.0,SRB,77.0,2003.0,2011,24.0,31.0,8.0,13.0
2,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Semi-Finals,32,2,23,...,Novak Djokovic,1987.0,SRB,77.0,2003.0,2010,23.0,24.0,7.0,4.0
3,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Quarter-Finals,66,2,17,...,Novak Djokovic,1987.0,SRB,77.0,2003.0,2010,23.0,23.0,7.0,5.0
4,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Round of 32,26,2,18,...,Novak Djokovic,1987.0,SRB,77.0,2003.0,2010,23.0,22.0,7.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,Juan Manuel Benitez Chavarriaga,184,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 16,1011,2,18,...,NaN,NaN,NaN,NaN,NaN,2017,NaN,23.0,NaN,NaN
4928,Marvin Moeller,178,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,Round of 32,1298,3,28,...,Marvin Moeller,1999.0,GER,69.0,NaN,2021,22.0,NaN,NaN,NaN
4929,Marvin Moeller,178,Switzerland F5,"Sion, Switzerland",Clay,15000.0,Round of 32,545,3,29,...,Marvin Moeller,1999.0,GER,69.0,NaN,2017,18.0,24.0,NaN,NaN
4930,Maxence Beauge,183,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 32,941,2,20,...,NaN,NaN,NaN,NaN,NaN,2017,NaN,NaN,NaN,NaN
4931,Nicolas Parizzia,184,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,Round of 32,2048,3,26,...,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,NaN

In [98]:
df_merged1 = df_merged1.drop(['full_name_y','full_name_x'],axis=1)

In [99]:
df_merged1

,Player1_Name,Player1_Height,Tournament,Location,Ground,Prize,GameRound,Player2_Rank,Num_Sets,TotalPoints,...,turned_pro_x,birth_year_y,flag_code_y,Player1_Weight,turned_pro_y,Start_year,Player1_age,Player2_age,Player1_turned_pro,Player2_turned_pro
0,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 16,64,2,15,...,2002.0,1987.0,SRB,77.0,2003.0,2011,24.0,29.0,8.0,9.0
1,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 32,47,3,30,...,1998.0,1987.0,SRB,77.0,2003.0,2011,24.0,31.0,8.0,13.0
2,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Semi-Finals,32,2,23,...,2006.0,1987.0,SRB,77.0,2003.0,2010,23.0,24.0,7.0,4.0
3,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Quarter-Finals,66,2,17,...,2005.0,1987.0,SRB,77.0,2003.0,2010,23.0,23.0,7.0,5.0
4,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Round of 32,26,2,18,...,2004.0,1987.0,SRB,77.0,2003.0,2010,23.0,22.0,7.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,Juan Manuel Benitez Chavarriaga,184,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 16,1011,2,18,...,NaN,NaN,NaN,NaN,NaN,2017,NaN,23.0,NaN,NaN
4928,Marvin Moeller,178,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,Round of 32,1298,3,28,...,NaN,1999.0,GER,69.0,NaN,2021,22.0,NaN,NaN,NaN
4929,Marvin Moeller,178,Switzerland F5,"Sion, Switzerland",Clay,15000.0,Round of 32,545,3,29,...,NaN,1999.0,GER,69.0,NaN,2017,18.0,24.0,NaN,NaN
4930,Maxence Beauge,183,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 32,941,2,20,...,NaN,NaN,NaN,NaN,NaN,2017,NaN,NaN,NaN,NaN
4931,Nicolas Parizzia,184,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,Round of 32,2048,3,26,...,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,NaN

In [100]:

# Especifique a nova ordem das colunas
nova_ordem = ['Player1_Name', 'Player1_Height','Player1_Weight','Player1_turned_pro','Player1_age','Player1_Rank','Tournament', 'Location', 'Ground','Prize', 'GameRound',
       'Start_Date', 'End_Date','Tornament_Days', 'Num_Sets', 'TotalPoints','GameId', 'Player2_Name','Player2_Height','Player2_Weight' ,'Player2_turned_pro','Player2_age','Player2_Rank', 'Rank_Diff', 'birth_year_x',
       'flag_code_x', 'turned_pro_x', 'birth_year_y',
       'flag_code_y', 'turned_pro_y', 'Start_year'
 
       ]

# Reorganize as colunas do DataFrame
df_merged1 = df_merged1.reindex(columns=nova_ordem)

# Exiba o DataFrame com as colunas organizadas
df_merged1

,Player1_Name,Player1_Height,Player1_Weight,Player1_turned_pro,Player1_age,Player1_Rank,Tournament,Location,Ground,Prize,...,Player2_age,Player2_Rank,Rank_Diff,birth_year_x,flag_code_x,turned_pro_x,birth_year_y,flag_code_y,turned_pro_y,Start_year
0,Novak Djokovic,188,77.0,8.0,24.0,1,Basel,"Basel, Switzerland",Hard,1308100.0,...,29.0,64,63,1982.0,POL,2002.0,1987.0,SRB,2003.0,2011
1,Novak Djokovic,188,77.0,8.0,24.0,1,Basel,"Basel, Switzerland",Hard,1308100.0,...,31.0,47,46,1980.0,BEL,1998.0,1987.0,SRB,2003.0,2011
2,Novak Djokovic,188,77.0,7.0,23.0,3,Basel,"Basel, Switzerland",Hard,1225000.0,...,24.0,32,29,1986.0,SRB,2006.0,1987.0,SRB,2003.0,2010
3,Novak Djokovic,188,77.0,7.0,23.0,3,Basel,"Basel, Switzerland",Hard,1225000.0,...,23.0,66,63,1987.0,NED,2005.0,1987.0,SRB,2003.0,2010
4,Novak Djokovic,188,77.0,7.0,23.0,3,Basel,"Basel, Switzerland",Hard,1225000.0,...,22.0,26,23,1988.0,LAT,2004.0,1987.0,SRB,2003.0,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,Juan Manuel Benitez Chavarriaga,184,NaN,NaN,NaN,646,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,...,23.0,1011,365,1994.0,SUI,NaN,NaN,NaN,NaN,2017
4928,Marvin Moeller,178,69.0,NaN,22.0,614,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,...,NaN,1298,684,NaN,NaN,NaN,1999.0,GER,NaN,2021
4929,Marvin Moeller,178,69.0,NaN,18.0,1128,Switzerland F5,"Sion, Switzerland",Clay,15000.0,...,24.0,545,583,1993.0,GER,NaN,1999.0,GER,NaN,2017
4930,Maxence Beauge,183,NaN,NaN,NaN,1325,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,...,NaN,941,384,NaN,NaN,NaN,NaN,NaN,NaN,2017
4931,Nicolas Parizzia,184,NaN,NaN,NaN,1672,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,...,NaN,2048,376,NaN,NaN,NaN,NaN,NaN,NaN,2021

In [101]:
df_merged1.rename(columns={'flag_code_y': 'Player1_flag'}, inplace=True)
df_merged1.rename(columns={'weight_kg_x': 'Player2_flag'}, inplace=True)

In [102]:
df_merged1

,Player1_Name,Player1_Height,Player1_Weight,Player1_turned_pro,Player1_age,Player1_Rank,Tournament,Location,Ground,Prize,...,Player2_age,Player2_Rank,Rank_Diff,birth_year_x,flag_code_x,turned_pro_x,birth_year_y,Player1_flag,turned_pro_y,Start_year
0,Novak Djokovic,188,77.0,8.0,24.0,1,Basel,"Basel, Switzerland",Hard,1308100.0,...,29.0,64,63,1982.0,POL,2002.0,1987.0,SRB,2003.0,2011
1,Novak Djokovic,188,77.0,8.0,24.0,1,Basel,"Basel, Switzerland",Hard,1308100.0,...,31.0,47,46,1980.0,BEL,1998.0,1987.0,SRB,2003.0,2011
2,Novak Djokovic,188,77.0,7.0,23.0,3,Basel,"Basel, Switzerland",Hard,1225000.0,...,24.0,32,29,1986.0,SRB,2006.0,1987.0,SRB,2003.0,2010
3,Novak Djokovic,188,77.0,7.0,23.0,3,Basel,"Basel, Switzerland",Hard,1225000.0,...,23.0,66,63,1987.0,NED,2005.0,1987.0,SRB,2003.0,2010
4,Novak Djokovic,188,77.0,7.0,23.0,3,Basel,"Basel, Switzerland",Hard,1225000.0,...,22.0,26,23,1988.0,LAT,2004.0,1987.0,SRB,2003.0,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,Juan Manuel Benitez Chavarriaga,184,NaN,NaN,NaN,646,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,...,23.0,1011,365,1994.0,SUI,NaN,NaN,NaN,NaN,2017
4928,Marvin Moeller,178,69.0,NaN,22.0,614,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,...,NaN,1298,684,NaN,NaN,NaN,1999.0,GER,NaN,2021
4929,Marvin Moeller,178,69.0,NaN,18.0,1128,Switzerland F5,"Sion, Switzerland",Clay,15000.0,...,24.0,545,583,1993.0,GER,NaN,1999.0,GER,NaN,2017
4930,Maxence Beauge,183,NaN,NaN,NaN,1325,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,...,NaN,941,384,NaN,NaN,NaN,NaN,NaN,NaN,2017
4931,Nicolas Parizzia,184,NaN,NaN,NaN,1672,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,...,NaN,2048,376,NaN,NaN,NaN,NaN,NaN,NaN,2021

## WEB SCRAPING

In [103]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

In [55]:
df_merged1[['Player1_Name','Player1_flag']]

                         Player1_Name Player1_flag
0                      Novak Djokovic          SRB
1                      Novak Djokovic          SRB
2                      Novak Djokovic          SRB
3                      Novak Djokovic          SRB
4                      Novak Djokovic          SRB
...                               ...          ...
4927  Juan Manuel Benitez Chavarriaga          NaN
4928                   Marvin Moeller          GER
4929                   Marvin Moeller          GER
4930                   Maxence Beauge          NaN
4931                 Nicolas Parizzia          NaN

[4932 rows x 2 columns]

In [104]:
(df_merged1['Player1_flag'].isna().sum())

768

In [112]:
null_flags = df_merged1.loc[df_merged1['Player1_flag'].isnull()]
null_names = null_flags['Player1_Name'].unique()
print(null_names)

['Matteo Berrettini' 'Cristian Garin' 'Ugo Humbert' 'Miomir Kecmanovic'
 'Federico Coria' 'Soonwoo Kwon' 'Dominik Koepfer' 'Hugo Gaston'
 'Daniel Altmaier' 'Oscar Otte' 'Alexei Popyrin' 'Jiri Lehecka'
 'Tomas Martin Etcheverry' 'Juan Pablo Varillas' 'Juan Manuel Cerundolo'
 'Roman Safiullin' 'Hugo Grenier' 'Dominic Stricker' 'Vit Kopriva'
 'Pavel Kotov' 'Marc-Andrea Huesler' 'Gian Marco Moroni' 'Jesper De Jong'
 'Jurij Rodionov' 'Kacper Zuk' 'Antoine Hoang' 'Juan Pablo Ficovich'
 'Vitaliy Sachko' 'Matheus Pucinelli De Almeida' 'Ryan Peniston'
 'Lukas Klein' 'Evan Furness' 'Arthur Cazaux' 'Nicolas Moreno De Alboran'
 'Rinky Hijikata' 'Francesco Forti' 'Matteo Martineau' 'Gijs Brouwer'
 'Shintaro Mochizuki' 'Oliver Crawford' 'Filippo Baldi'
 'Nicholas David Ionel' 'Michael Vrbensky' 'Michail Pervolarakis'
 'Pol Martin Tiffon' 'Otto Virtanen' 'Giovanni Fonio' 'Christopher Heyman'
 'Marek Gengel' 'Harold Mayot' 'Jakub Paul' 'Oscar Jose Gutierrez'
 'Mateus Alves' 'Moez Echargui' 'Valentin Vacherot' 'Jacopo Berrettini'
 'Edan Leshem' 'Riccardo Balzerani' 'Quentin Folliot' 'Julian Ocleppo'
 'Tim Handel' 'Remy Bertola' 'Tristan Schoolkate' 'Leandro Riedi'
 'Patrik Rikl' 'Patrick Kypson' 'Mick Veldheer' 'Luca Castelnuovo'
 'Petr Nouza' 'Marco Miceli' 'Ronald Slobodchikov' 'Marvin Netuschil'
 'Patrik Niklas-Salminen' 'Fabrizio Ornago' 'Marko Miladinovic'
 'Luca Tomasetto' 'Louis Tessa' 'Louroi Martinez' 'Mirko Martinez'
 'Lorenzo Frigerio' 'Paul Woerner' 'Mick Lescure' 'Manfred Fellin'
 'Valentin Guenther' 'Riccardo Maiga' 'Yannik Steinegger'
 'Raphael Baltensperger' 'Henry Von Der Schulenburg' 'Luca Staeheli'
 'Paul Cayre' 'Patrik Hartmeier' 'Constantin Frantzen' 'Petr Michnev'
 'George Von Massow' 'Lukas Ollert' 'Jorge Montero'
 'Marcos Giraldi Requena' 'Jonathan Kanar' 'Christian Hirschmueller'
 'Mischa Lanz' 'Kevin Griekspoor' 'Filipp Kekercheni' 'Jordan Ubiergo'
 'Raleigh Smith' 'Bastian Wagner' 'Pirmin Haenle' 'Luca Pancaldi'
 'Matthieu Roy' 'Andrew Ruppli' 'Riccardo Sinicropi' 'Federico Maccari'
 'Marko Osmakcic' 'Nino Portales' 'Enzo Sommer' 'Luca Keist'
 'Christian Trubrig' 'Dimitar Grabul' 'Michael Bois' 'Jakub Lustyk'
 'Nicolas Rosenzweig' 'David Simunek' 'Oliver Mrose' 'Alexandre Massa'
 'Marko Danis' 'Giacomo Oradini' 'Romain Dauzet' 'Yuri Bezeruk'
 'Franck Pepe' 'Jiri Skoloudik' 'Enrico Iannuzzi' 'Matthias Kolbe'
 'Mark-Alexander Kepler' 'Nikolai Haessig' 'Matthieu Vierin'
 'Andrea Falgheri' 'Jan Marek' 'Thomas Cazes-Carrere' 'Jeremy Blandin'
 'Baptiste Bayet' 'David Novak' 'Jean Zietsman' 'Stefano Valenti'
 'Alberto Giraudo' 'Charles Roche' 'Raphael Hemmeler' 'Antoine Hamard'
 'Giuseppe Menga' 'Matteo Volante' 'Alessandro Da Col' 'Daniel Stoehr'
 'Ludwig Pellerin' 'Dekel Valtzer' 'Alessandro Piccari' 'Fabio Colangelo'
 'David Klier' 'Matteo Galli' 'Leonel Alberti' 'Marco Pedrini'
 'Mike Scheidweiler' 'Laurent Silvy' 'Luca Stoppini' 'Goncalo Nicau'
 'Stefan Kilchhofer' 'Charly Villeneuve' 'Dominique Coene' 'Massimo Ocera'
 'Tobias Koeck' 'Benoit Bottero' 'Ross Connolly' 'Daniel Muller'
 'Tommaso Cafferata' 'Miha Gregorc' 'Sebastien Louis' 'Andreas Kauntz'
 'David Stojan' 'Andrea Serra' 'Carl-Henrik Hansen' 'Marc Canovas'
 'Julien Burgnard' 'Petr Dezort' 'Jiri Vencl' 'Jun Kato' 'Jan Riha'
 'Florian Jeschonek' 'Patrick Sebastiani' 'Luben Pampoulov'
 'Daniel Lesske' 'Christian Dillschneider' 'Heiko Bollich' 'Igor Brukner'
 'Martin Hochstrasser' 'Aaron Schmid' 'Adrian Bodmer' 'Alafia Ayeni'
 'Alastair Gray' 'Alejandro Davidovich Fokina' 'Alejandro Tabilo'
 'Alejo Vilaro' 'Aleksandar Kovacevic' 'Alen Avidzba' 'Alex Molcan'
 'Alexander Shevchenko' 'Alexander Weis' 'Alexis Gautier' 'Andrea Basso'
 'Andrew Paulson' 'Andrew Watson' 'Anton Chekhov' 'Anton Matusevich'
 'Arthur Reymond' 'Arthur Rinderknech' 'Aziz Dougaz' 'Baptiste Crepatte'
 'Benjamin Bonzi' 'Benjamin Hassan' 'Borna Gojo' 'Camilo Ugo Carabelli'
 'Clement Tabur' 'Damien Wenger' 'Dan Added' 'Daniel Cukierman'
 'Danylo Kalenichenko' 'David Pichler' 'David Poljak' 'Davide Galoppini'
 'Dominik Boehler' 'Edoardo Eremin' 'Edoardo Graziani' 'Emiliano Maggioli'
 'Fabien Reboul' 'Federico Arnaboldi' 'Federico Iannaccone' 'Florent Bax'
 'Georgii Kravchenko' 'Giovanni Oradini' 'Holger Rune' 'Hugo Voljacques'
 'Jakob Aichhorn' 'Jakob Sude' 'Jerome Kym'
 'Juan Manuel Benitez Chavarriaga' 'Maxence Beauge' 'Nicolas Parizzia']