## Librarys

In [4]:
import pandas as pd
import matplotlib.pyplot as plt

## Leitura de um dataset novo

In [5]:
df = pd.read_csv('dataset_tennis.csv')

In [6]:
df

,player_id,player_slug,first_name,last_name,player_url,flag_code,residence,birthplace,birthdate,birth_year,birth_month,birth_day,turned_pro,weight_lbs,weight_kg,height_ft,height_inches,height_cm,handedness,backhand
0,a002,ricardo-acuna,Ricardo,Acuna,http://www.atpworldtour.com/en/players/ricardo...,CHI,"Jupiter, FL, USA","Santiago, Chile",1958.01.13,1958.0,1.0,13.0,0.0,150.0,68.0,"5'9""",69.0,175.0,NaN,NaN
1,a001,sadiq-abdullahi,Sadiq,Abdullahi,http://www.atpworldtour.com/en/players/sadiq-a...,NGR,NaN,NaN,1960.02.02,1960.0,2.0,2.0,0.0,0.0,0.0,"0'0""",0.0,0.0,NaN,NaN
2,a005,nelson-aerts,Nelson,Aerts,http://www.atpworldtour.com/en/players/nelson-...,BRA,NaN,"Cachoeira Do Sul, Brazil",1963.04.25,1963.0,4.0,25.0,0.0,165.0,75.0,"6'2""",74.0,188.0,NaN,NaN
3,a004,egan-adams,Egan,Adams,http://www.atpworldtour.com/en/players/egan-ad...,USA,"Palmetto, FL, USA","Miami Beach, FL, USA",1959.06.15,1959.0,6.0,15.0,0.0,160.0,73.0,"5'10""",70.0,178.0,NaN,NaN
4,a006,ronald-agenor,Ronald,Agenor,http://www.atpworldtour.com/en/players/ronald-...,USA,"Beverly Hills, California, USA","Rabat, Morocco",1964.11.13,1964.0,11.0,13.0,1983.0,180.0,82.0,"5'11""",71.0,180.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10907,z435,a-zorab,A.,Zorab,http://www.atpworldtour.com/en/players/a-zorab...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10908,z437,j-zimmermann,J.,Zimmermann,http://www.atpworldtour.com/en/players/j-zimme...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10909,z436,g-zinn,G.,Zinn,http://www.atpworldtour.com/en/players/g-zinn/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10910,z440,c-zenger,C.,Zenger,http://www.atpworldtour.com/en/players/c-zenge...,GER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10911,z442,a-ziffo,A.,Ziffo,http://www.atpworldtour.com/en/players/a-ziffo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:

df1 = pd.read_csv('switzerland_final.csv')

### Criação de uma nova coluna com novo dataset

In [8]:
df['full_name'] = df['first_name'] + ' ' + df['last_name']

In [9]:
df_merged = pd.merge(df1, df[['full_name', 'birth_year','flag_code','weight_kg','turned_pro','height_cm']], left_on='Player1_Name', right_on='full_name', how='left')

In [10]:
df_merged

,Unnamed: 0,Player1_Name,Player1_Height,Tournament,Location,Ground,Prize,GameRound,Player2_Rank,Num_Sets,...,Player2_Name,Player2_Height,Player1_Rank,Rank_Diff,full_name,birth_year,flag_code,weight_kg,turned_pro,height_cm
0,0,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 16,64,2,...,Lukasz Kubot,191,1,63,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
1,1,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 32,47,3,...,Xavier Malisse,185,1,46,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
2,2,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Semi-Finals,32,2,...,Viktor Troicki,193,3,29,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
3,3,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Quarter-Finals,66,2,...,Robin Haase,191,3,63,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
4,4,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Round of 32,26,2,...,Ernests Gulbis,191,3,23,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4922,4922,Juan Manuel Benitez Chavarriaga,184,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 16,1011,2,...,Loic Perret,188,646,365,NaN,NaN,NaN,NaN,NaN,NaN
4923,4923,Marvin Moeller,178,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,Round of 32,1298,3,...,Patrik Hartmeier,184,614,684,Marvin Moeller,1999.0,GER,69.0,NaN,178.0
4924,4924,Marvin Moeller,178,Switzerland F5,"Sion, Switzerland",Clay,15000.0,Round of 32,545,3,...,Pascal Meis,180,1128,583,Marvin Moeller,1999.0,GER,69.0,NaN,178.0
4925,4925,Maxence Beauge,183,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 32,941,2,...,Issei Okamura,170,1325,384,NaN,NaN,NaN,NaN,NaN,NaN
4926,4926,Nicolas Parizzia,184,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,Round of 32,2048,3,...,Gian Luca Tanner,191,1672,376,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_merged = pd.merge(df1, df[['full_name', 'birth_year','flag_code','weight_kg','turned_pro','height_cm']], left_on='Player2_Name', right_on='full_name', how='left')

In [12]:
df_merged

,Unnamed: 0,Player1_Name,Player1_Height,Tournament,Location,Ground,Prize,GameRound,Player2_Rank,Num_Sets,...,Player2_Name,Player2_Height,Player1_Rank,Rank_Diff,full_name,birth_year,flag_code,weight_kg,turned_pro,height_cm
0,0,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 16,64,2,...,Lukasz Kubot,191,1,63,Lukasz Kubot,1982.0,POL,86.0,2002.0,191.0
1,1,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 32,47,3,...,Xavier Malisse,185,1,46,Xavier Malisse,1980.0,BEL,83.0,1998.0,185.0
2,2,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Semi-Finals,32,2,...,Viktor Troicki,193,3,29,Viktor Troicki,1986.0,SRB,86.0,2006.0,193.0
3,3,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Quarter-Finals,66,2,...,Robin Haase,191,3,63,Robin Haase,1987.0,NED,71.0,2005.0,191.0
4,4,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Round of 32,26,2,...,Ernests Gulbis,191,3,23,Ernests Gulbis,1988.0,LAT,88.0,2004.0,193.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,4922,Juan Manuel Benitez Chavarriaga,184,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 16,1011,2,...,Loic Perret,188,646,365,Loic Perret,1994.0,SUI,NaN,NaN,NaN
4928,4923,Marvin Moeller,178,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,Round of 32,1298,3,...,Patrik Hartmeier,184,614,684,NaN,NaN,NaN,NaN,NaN,NaN
4929,4924,Marvin Moeller,178,Switzerland F5,"Sion, Switzerland",Clay,15000.0,Round of 32,545,3,...,Pascal Meis,180,1128,583,Pascal Meis,1993.0,GER,NaN,NaN,NaN
4930,4925,Maxence Beauge,183,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 32,941,2,...,Issei Okamura,170,1325,384,NaN,NaN,NaN,NaN,NaN,NaN
4931,4926,Nicolas Parizzia,184,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,Round of 32,2048,3,...,Gian Luca Tanner,191,1672,376,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df_merged.to_csv('jogadores_year.csv', index=False)

In [14]:
df2 = pd.read_csv('jogadores_year.csv')

In [15]:
df_merged1 = pd.merge(df2, df[['full_name', 'birth_year','flag_code','weight_kg','turned_pro','height_cm']], left_on='Player1_Name', right_on='full_name', how='left')

In [16]:
df_merged1

,Unnamed: 0,Player1_Name,Player1_Height,Tournament,Location,Ground,Prize,GameRound,Player2_Rank,Num_Sets,...,flag_code_x,weight_kg_x,turned_pro_x,height_cm_x,full_name_y,birth_year_y,flag_code_y,weight_kg_y,turned_pro_y,height_cm_y
0,0,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 16,64,2,...,POL,86.0,2002.0,191.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
1,1,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 32,47,3,...,BEL,83.0,1998.0,185.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
2,2,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Semi-Finals,32,2,...,SRB,86.0,2006.0,193.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
3,3,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Quarter-Finals,66,2,...,NED,71.0,2005.0,191.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
4,4,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Round of 32,26,2,...,LAT,88.0,2004.0,193.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,4922,Juan Manuel Benitez Chavarriaga,184,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 16,1011,2,...,SUI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4928,4923,Marvin Moeller,178,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,Round of 32,1298,3,...,NaN,NaN,NaN,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,178.0
4929,4924,Marvin Moeller,178,Switzerland F5,"Sion, Switzerland",Clay,15000.0,Round of 32,545,3,...,GER,NaN,NaN,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,178.0
4930,4925,Maxence Beauge,183,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 32,941,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4931,4926,Nicolas Parizzia,184,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,Round of 32,2048,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df_merged1['Start_Date'] = pd.to_datetime(df_merged1['Start_Date'], format='%Y-%m-%d')

In [18]:
df_merged1['Player1_age'] = df_merged1['Start_Date'].dt.year - df_merged1['birth_year_y']

In [19]:
df_merged1['Player2_age'] = df_merged1['Start_Date'].dt.year - df_merged1['birth_year_x']

In [20]:
df_merged1

,Unnamed: 0,Player1_Name,Player1_Height,Tournament,Location,Ground,Prize,GameRound,Player2_Rank,Num_Sets,...,turned_pro_x,height_cm_x,full_name_y,birth_year_y,flag_code_y,weight_kg_y,turned_pro_y,height_cm_y,Player1_age,Player2_age
0,0,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 16,64,2,...,2002.0,191.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,24.0,29.0
1,1,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 32,47,3,...,1998.0,185.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,24.0,31.0
2,2,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Semi-Finals,32,2,...,2006.0,193.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,23.0,24.0
3,3,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Quarter-Finals,66,2,...,2005.0,191.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,23.0,23.0
4,4,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Round of 32,26,2,...,2004.0,193.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,23.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,4922,Juan Manuel Benitez Chavarriaga,184,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 16,1011,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0
4928,4923,Marvin Moeller,178,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,Round of 32,1298,3,...,NaN,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,178.0,22.0,NaN
4929,4924,Marvin Moeller,178,Switzerland F5,"Sion, Switzerland",Clay,15000.0,Round of 32,545,3,...,NaN,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,178.0,18.0,24.0
4930,4925,Maxence Beauge,183,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 32,941,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4931,4926,Nicolas Parizzia,184,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,Round of 32,2048,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Variável Peso

In [21]:
df_merged1['Player1_Height'] = df_merged1['Player1_Height'].fillna(df_merged1['height_cm_y'])

df_merged1

,Unnamed: 0,Player1_Name,Player1_Height,Tournament,Location,Ground,Prize,GameRound,Player2_Rank,Num_Sets,...,turned_pro_x,height_cm_x,full_name_y,birth_year_y,flag_code_y,weight_kg_y,turned_pro_y,height_cm_y,Player1_age,Player2_age
0,0,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 16,64,2,...,2002.0,191.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,24.0,29.0
1,1,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 32,47,3,...,1998.0,185.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,24.0,31.0
2,2,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Semi-Finals,32,2,...,2006.0,193.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,23.0,24.0
3,3,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Quarter-Finals,66,2,...,2005.0,191.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,23.0,23.0
4,4,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Round of 32,26,2,...,2004.0,193.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,23.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,4922,Juan Manuel Benitez Chavarriaga,184,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 16,1011,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0
4928,4923,Marvin Moeller,178,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,Round of 32,1298,3,...,NaN,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,178.0,22.0,NaN
4929,4924,Marvin Moeller,178,Switzerland F5,"Sion, Switzerland",Clay,15000.0,Round of 32,545,3,...,NaN,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,178.0,18.0,24.0
4930,4925,Maxence Beauge,183,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 32,941,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4931,4926,Nicolas Parizzia,184,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,Round of 32,2048,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:

df_merged1['Player2_Height'] = df_merged1['Player2_Height'].fillna(df_merged1['height_cm_x'])

df_merged1

,Unnamed: 0,Player1_Name,Player1_Height,Tournament,Location,Ground,Prize,GameRound,Player2_Rank,Num_Sets,...,turned_pro_x,height_cm_x,full_name_y,birth_year_y,flag_code_y,weight_kg_y,turned_pro_y,height_cm_y,Player1_age,Player2_age
0,0,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 16,64,2,...,2002.0,191.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,24.0,29.0
1,1,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 32,47,3,...,1998.0,185.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,24.0,31.0
2,2,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Semi-Finals,32,2,...,2006.0,193.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,23.0,24.0
3,3,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Quarter-Finals,66,2,...,2005.0,191.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,23.0,23.0
4,4,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Round of 32,26,2,...,2004.0,193.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,188.0,23.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,4922,Juan Manuel Benitez Chavarriaga,184,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 16,1011,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0
4928,4923,Marvin Moeller,178,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,Round of 32,1298,3,...,NaN,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,178.0,22.0,NaN
4929,4924,Marvin Moeller,178,Switzerland F5,"Sion, Switzerland",Clay,15000.0,Round of 32,545,3,...,NaN,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,178.0,18.0,24.0
4930,4925,Maxence Beauge,183,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 32,941,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4931,4926,Nicolas Parizzia,184,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,Round of 32,2048,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
print('Valores nulos Player1') 
df_merged1['Player1_Height'].isna().sum()

Valores nulos Player1

0

In [24]:
print('Valores nulos Player2') 
df_merged1['Player2_Height'].isna().sum()

Valores nulos Player2

0

### Drop nas colunas não necessárias

In [25]:
df_merged1 = df_merged1.drop(['height_cm_x','height_cm_y','Unnamed: 0'],axis=1)

In [26]:
df_merged1

,Player1_Name,Player1_Height,Tournament,Location,Ground,Prize,GameRound,Player2_Rank,Num_Sets,TotalPoints,...,flag_code_x,weight_kg_x,turned_pro_x,full_name_y,birth_year_y,flag_code_y,weight_kg_y,turned_pro_y,Player1_age,Player2_age
0,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 16,64,2,15,...,POL,86.0,2002.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,24.0,29.0
1,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 32,47,3,30,...,BEL,83.0,1998.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,24.0,31.0
2,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Semi-Finals,32,2,23,...,SRB,86.0,2006.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,23.0,24.0
3,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Quarter-Finals,66,2,17,...,NED,71.0,2005.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,23.0,23.0
4,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Round of 32,26,2,18,...,LAT,88.0,2004.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,23.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,Juan Manuel Benitez Chavarriaga,184,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 16,1011,2,18,...,SUI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0
4928,Marvin Moeller,178,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,Round of 32,1298,3,28,...,NaN,NaN,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,22.0,NaN
4929,Marvin Moeller,178,Switzerland F5,"Sion, Switzerland",Clay,15000.0,Round of 32,545,3,29,...,GER,NaN,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,18.0,24.0
4930,Maxence Beauge,183,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 32,941,2,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4931,Nicolas Parizzia,184,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,Round of 32,2048,3,26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Rename as variáveis

In [27]:
df_merged1.rename(columns={'weight_kg_y': 'Player1_Weight'}, inplace=True)
df_merged1.rename(columns={'weight_kg_x': 'Player2_Weight'}, inplace=True)

In [28]:
df_merged1

,Player1_Name,Player1_Height,Tournament,Location,Ground,Prize,GameRound,Player2_Rank,Num_Sets,TotalPoints,...,flag_code_x,Player2_Weight,turned_pro_x,full_name_y,birth_year_y,flag_code_y,Player1_Weight,turned_pro_y,Player1_age,Player2_age
0,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 16,64,2,15,...,POL,86.0,2002.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,24.0,29.0
1,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 32,47,3,30,...,BEL,83.0,1998.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,24.0,31.0
2,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Semi-Finals,32,2,23,...,SRB,86.0,2006.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,23.0,24.0
3,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Quarter-Finals,66,2,17,...,NED,71.0,2005.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,23.0,23.0
4,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Round of 32,26,2,18,...,LAT,88.0,2004.0,Novak Djokovic,1987.0,SRB,77.0,2003.0,23.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,Juan Manuel Benitez Chavarriaga,184,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 16,1011,2,18,...,SUI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0
4928,Marvin Moeller,178,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,Round of 32,1298,3,28,...,NaN,NaN,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,22.0,NaN
4929,Marvin Moeller,178,Switzerland F5,"Sion, Switzerland",Clay,15000.0,Round of 32,545,3,29,...,GER,NaN,NaN,Marvin Moeller,1999.0,GER,69.0,NaN,18.0,24.0
4930,Maxence Beauge,183,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 32,941,2,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4931,Nicolas Parizzia,184,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,Round of 32,2048,3,26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Criação anos de experiência

In [29]:
df_merged1['Player1_turned_pro'] = df_merged1['Start_Date'].dt.year - df_merged1['turned_pro_y']
df_merged1['Player2_turned_pro'] = df_merged1['Start_Date'].dt.year - df_merged1['turned_pro_x']

df_merged1

#### Drop colounas não necessárias

In [30]:
df_merged1 = df_merged1.drop(['full_name_y','full_name_x'],axis=1)

In [31]:
df_merged1

,Player1_Name,Player1_Height,Tournament,Location,Ground,Prize,GameRound,Player2_Rank,Num_Sets,TotalPoints,...,Player2_Weight,turned_pro_x,birth_year_y,flag_code_y,Player1_Weight,turned_pro_y,Player1_age,Player2_age,Player1_turned_pro,Player2_turned_pro
0,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 16,64,2,15,...,86.0,2002.0,1987.0,SRB,77.0,2003.0,24.0,29.0,8.0,9.0
1,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1308100.0,Round of 32,47,3,30,...,83.0,1998.0,1987.0,SRB,77.0,2003.0,24.0,31.0,8.0,13.0
2,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Semi-Finals,32,2,23,...,86.0,2006.0,1987.0,SRB,77.0,2003.0,23.0,24.0,7.0,4.0
3,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Quarter-Finals,66,2,17,...,71.0,2005.0,1987.0,SRB,77.0,2003.0,23.0,23.0,7.0,5.0
4,Novak Djokovic,188,Basel,"Basel, Switzerland",Hard,1225000.0,Round of 32,26,2,18,...,88.0,2004.0,1987.0,SRB,77.0,2003.0,23.0,22.0,7.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,Juan Manuel Benitez Chavarriaga,184,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 16,1011,2,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,NaN,NaN
4928,Marvin Moeller,178,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,Round of 32,1298,3,28,...,NaN,NaN,1999.0,GER,69.0,NaN,22.0,NaN,NaN,NaN
4929,Marvin Moeller,178,Switzerland F5,"Sion, Switzerland",Clay,15000.0,Round of 32,545,3,29,...,NaN,NaN,1999.0,GER,69.0,NaN,18.0,24.0,NaN,NaN
4930,Maxence Beauge,183,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,Round of 32,941,2,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4931,Nicolas Parizzia,184,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,Round of 32,2048,3,26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Estruturar colunas

In [32]:
nova_ordem = ['Player1_Name', 'Player1_Height','Player1_Weight','Player1_turned_pro','Player1_age','Player1_Rank','Tournament', 'Location', 'Ground','Prize', 'GameRound',
       'Start_Date', 'End_Date','Tornament_Days', 'Num_Sets', 'TotalPoints','GameId', 'Player2_Name','Player2_Height','Player2_Weight' ,'Player2_turned_pro','Player2_age','Player2_Rank', 'Rank_Diff', 'birth_year_x',
       'flag_code_x', 'turned_pro_x', 'birth_year_y',
       'flag_code_y', 'turned_pro_y', 'Start_year'
 
       ]


df_merged1 = df_merged1.reindex(columns=nova_ordem)


df_merged1

,Player1_Name,Player1_Height,Player1_Weight,Player1_turned_pro,Player1_age,Player1_Rank,Tournament,Location,Ground,Prize,...,Player2_age,Player2_Rank,Rank_Diff,birth_year_x,flag_code_x,turned_pro_x,birth_year_y,flag_code_y,turned_pro_y,Start_year
0,Novak Djokovic,188,77.0,8.0,24.0,1,Basel,"Basel, Switzerland",Hard,1308100.0,...,29.0,64,63,1982.0,POL,2002.0,1987.0,SRB,2003.0,NaN
1,Novak Djokovic,188,77.0,8.0,24.0,1,Basel,"Basel, Switzerland",Hard,1308100.0,...,31.0,47,46,1980.0,BEL,1998.0,1987.0,SRB,2003.0,NaN
2,Novak Djokovic,188,77.0,7.0,23.0,3,Basel,"Basel, Switzerland",Hard,1225000.0,...,24.0,32,29,1986.0,SRB,2006.0,1987.0,SRB,2003.0,NaN
3,Novak Djokovic,188,77.0,7.0,23.0,3,Basel,"Basel, Switzerland",Hard,1225000.0,...,23.0,66,63,1987.0,NED,2005.0,1987.0,SRB,2003.0,NaN
4,Novak Djokovic,188,77.0,7.0,23.0,3,Basel,"Basel, Switzerland",Hard,1225000.0,...,22.0,26,23,1988.0,LAT,2004.0,1987.0,SRB,2003.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,Juan Manuel Benitez Chavarriaga,184,NaN,NaN,NaN,646,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,...,23.0,1011,365,1994.0,SUI,NaN,NaN,NaN,NaN,NaN
4928,Marvin Moeller,178,69.0,NaN,22.0,614,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,...,NaN,1298,684,NaN,NaN,NaN,1999.0,GER,NaN,NaN
4929,Marvin Moeller,178,69.0,NaN,18.0,1128,Switzerland F5,"Sion, Switzerland",Clay,15000.0,...,24.0,545,583,1993.0,GER,NaN,1999.0,GER,NaN,NaN
4930,Maxence Beauge,183,NaN,NaN,NaN,1325,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,...,NaN,941,384,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4931,Nicolas Parizzia,184,NaN,NaN,NaN,1672,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,...,NaN,2048,376,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Rename colunaas flgas

In [33]:
df_merged1.rename(columns={'flag_code_y': 'Player1_flag'}, inplace=True)
df_merged1.rename(columns={'flag_code_x': 'Player2_flag'}, inplace=True)

In [34]:
df_merged1

,Player1_Name,Player1_Height,Player1_Weight,Player1_turned_pro,Player1_age,Player1_Rank,Tournament,Location,Ground,Prize,...,Player2_age,Player2_Rank,Rank_Diff,birth_year_x,Player2_flag,turned_pro_x,birth_year_y,Player1_flag,turned_pro_y,Start_year
0,Novak Djokovic,188,77.0,8.0,24.0,1,Basel,"Basel, Switzerland",Hard,1308100.0,...,29.0,64,63,1982.0,POL,2002.0,1987.0,SRB,2003.0,NaN
1,Novak Djokovic,188,77.0,8.0,24.0,1,Basel,"Basel, Switzerland",Hard,1308100.0,...,31.0,47,46,1980.0,BEL,1998.0,1987.0,SRB,2003.0,NaN
2,Novak Djokovic,188,77.0,7.0,23.0,3,Basel,"Basel, Switzerland",Hard,1225000.0,...,24.0,32,29,1986.0,SRB,2006.0,1987.0,SRB,2003.0,NaN
3,Novak Djokovic,188,77.0,7.0,23.0,3,Basel,"Basel, Switzerland",Hard,1225000.0,...,23.0,66,63,1987.0,NED,2005.0,1987.0,SRB,2003.0,NaN
4,Novak Djokovic,188,77.0,7.0,23.0,3,Basel,"Basel, Switzerland",Hard,1225000.0,...,22.0,26,23,1988.0,LAT,2004.0,1987.0,SRB,2003.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,Juan Manuel Benitez Chavarriaga,184,NaN,NaN,NaN,646,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,...,23.0,1011,365,1994.0,SUI,NaN,NaN,NaN,NaN,NaN
4928,Marvin Moeller,178,69.0,NaN,22.0,614,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,...,NaN,1298,684,NaN,NaN,NaN,1999.0,GER,NaN,NaN
4929,Marvin Moeller,178,69.0,NaN,18.0,1128,Switzerland F5,"Sion, Switzerland",Clay,15000.0,...,24.0,545,583,1993.0,GER,NaN,1999.0,GER,NaN,NaN
4930,Maxence Beauge,183,NaN,NaN,NaN,1325,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,...,NaN,941,384,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4931,Nicolas Parizzia,184,NaN,NaN,NaN,1672,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,...,NaN,2048,376,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Substituição dos Nan

In [35]:
df1 = pd.read_csv('atp_players.csv')
df1

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id
0,100001,Gardnar,Mulloy,R,19131122.0,USA,185.0,Q54544
1,100002,Pancho,Segura,R,19210620.0,ECU,168.0,Q54581
2,100003,Frank,Sedgman,R,19271002.0,AUS,180.0,Q962049
3,100004,Giuseppe,Merlo,R,19271011.0,ITA,NaN,Q1258752
4,100005,Richard,Gonzalez,R,19280509.0,USA,188.0,Q53554
...,...,...,...,...,...,...,...,...
60570,212133,Strahinja,Cejovic,U,NaN,SRB,NaN,NaN
60571,212134,Maxence,Rivet,U,NaN,FRA,NaN,NaN
60572,212135,Drona,Walia,U,NaN,IND,NaN,NaN
60573,212136,Roy,Horovitz,U,NaN,USA,NaN,NaN
60574,212137,Jelani,Sarr,U,NaN,USA,NaN,NaN

In [36]:
df1['full_name'] = df1['name_first']  + ' ' + df1['name_last']

In [37]:
df1

,player_id,name_first,name_last,hand,dob,ioc,height,wikidata_id,full_name
0,100001,Gardnar,Mulloy,R,19131122.0,USA,185.0,Q54544,Gardnar Mulloy
1,100002,Pancho,Segura,R,19210620.0,ECU,168.0,Q54581,Pancho Segura
2,100003,Frank,Sedgman,R,19271002.0,AUS,180.0,Q962049,Frank Sedgman
3,100004,Giuseppe,Merlo,R,19271011.0,ITA,NaN,Q1258752,Giuseppe Merlo
4,100005,Richard,Gonzalez,R,19280509.0,USA,188.0,Q53554,Richard Gonzalez
...,...,...,...,...,...,...,...,...,...
60570,212133,Strahinja,Cejovic,U,NaN,SRB,NaN,NaN,Strahinja Cejovic
60571,212134,Maxence,Rivet,U,NaN,FRA,NaN,NaN,Maxence Rivet
60572,212135,Drona,Walia,U,NaN,IND,NaN,NaN,Drona Walia
60573,212136,Roy,Horovitz,U,NaN,USA,NaN,NaN,Roy Horovitz
60574,212137,Jelani,Sarr,U,NaN,USA,NaN,NaN,Jelani Sarr

In [38]:
# Crie um dicionário que mapeia nomes de jogadores para códigos de país
jogador_pais_map = dict(zip(df1['full_name'], df1['ioc']))

# Use o método 'map' para mapear os códigos de país na coluna 'Player1_flag'
df_merged1['Player1_flag'] = df_merged1['Player1_Name'].map(jogador_pais_map)

In [39]:
# Crie um dicionário que mapeia nomes de jogadores para códigos de país
jogador_pais_map = dict(zip(df1['full_name'], df1['ioc']))

# Use o método 'map' para mapear os códigos de país na coluna 'Player1_flag'
df_merged1['Player2_flag'] = df_merged1['Player2_Name'].map(jogador_pais_map)

In [40]:
df_merged1

,Player1_Name,Player1_Height,Player1_Weight,Player1_turned_pro,Player1_age,Player1_Rank,Tournament,Location,Ground,Prize,...,Player2_age,Player2_Rank,Rank_Diff,birth_year_x,Player2_flag,turned_pro_x,birth_year_y,Player1_flag,turned_pro_y,Start_year
0,Novak Djokovic,188,77.0,8.0,24.0,1,Basel,"Basel, Switzerland",Hard,1308100.0,...,29.0,64,63,1982.0,POL,2002.0,1987.0,SRB,2003.0,NaN
1,Novak Djokovic,188,77.0,8.0,24.0,1,Basel,"Basel, Switzerland",Hard,1308100.0,...,31.0,47,46,1980.0,BEL,1998.0,1987.0,SRB,2003.0,NaN
2,Novak Djokovic,188,77.0,7.0,23.0,3,Basel,"Basel, Switzerland",Hard,1225000.0,...,24.0,32,29,1986.0,SRB,2006.0,1987.0,SRB,2003.0,NaN
3,Novak Djokovic,188,77.0,7.0,23.0,3,Basel,"Basel, Switzerland",Hard,1225000.0,...,23.0,66,63,1987.0,NED,2005.0,1987.0,SRB,2003.0,NaN
4,Novak Djokovic,188,77.0,7.0,23.0,3,Basel,"Basel, Switzerland",Hard,1225000.0,...,22.0,26,23,1988.0,LAT,2004.0,1987.0,SRB,2003.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,Juan Manuel Benitez Chavarriaga,184,NaN,NaN,NaN,646,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,...,23.0,1011,365,1994.0,FRA,NaN,NaN,COL,NaN,NaN
4928,Marvin Moeller,178,69.0,NaN,22.0,614,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,...,NaN,1298,684,NaN,SUI,NaN,1999.0,GER,NaN,NaN
4929,Marvin Moeller,178,69.0,NaN,18.0,1128,Switzerland F5,"Sion, Switzerland",Clay,15000.0,...,24.0,545,583,1993.0,GER,NaN,1999.0,GER,NaN,NaN
4930,Maxence Beauge,183,NaN,NaN,NaN,1325,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,...,NaN,941,384,NaN,JPN,NaN,NaN,FRA,NaN,NaN
4931,Nicolas Parizzia,184,NaN,NaN,NaN,1672,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,...,NaN,2048,376,NaN,SUI,NaN,NaN,SUI,NaN,NaN

In [41]:
null_flags = df_merged1.loc[df_merged1['Player1_flag'].isnull()]
null_names = null_flags['Player1_Name'].unique()
print(null_names)

['Felix Auger-Aliassime' 'Alex de Minaur' 'Albert Ramos-Vinolas'
 'Mackenzie McDonald' 'Jan-Lennard Struff' 'Soonwoo Kwon'
 'Pierre-Hugues Herbert' 'Marc-Andrea Huesler' 'Cedrik-Marcel Stebe'
 'Roberto Ortega-Olmedo' 'Guillermo Garcia-Lopez' 'Daniel Gimeno-Traver'
 'Johan Tatlot' 'Patrik Niklas-Salminen' 'Fred Gil' 'Tom Kocevar-Desman'
 'Inigo Cervantes' 'Thiemo de Bakker' 'Denis Matsukevich'
 'Francois-Arthur Vibert' 'Paul-Henri Mathieu' 'Andreas Haider-Maurer'
 'Teodor-Dacian Craciun' 'Woong-Sun Jun' 'Philipp Davydenko'
 'Dimitar Grabul' 'Alex Bogomolov Jr.' 'Haythem Abid'
 'Nuttanon Kadchapanan' 'Arnau Brugues-Davi' 'Gabriel Trujillo-Soler'
 'Juan-Martin Aranguren' 'Treat Huey' 'Mark-Alexander Kepler'
 'Pablo Martin-Adalia' 'Thomas Cazes-Carrere' 'Jan-Michael Gambill'
 'Jean-Rene Lisnard' 'Jose Antonio Sanchez-de Luna' "Massimo Dell'Acqua"
 'Jordi Marse-Vidri' 'Jean-Christophe Faurel' 'Bartolome Salva-Vidal'
 'Jean-Claude Scherrer' 'Juan Albert Viloca-Puig' 'Juan-Pablo Guzman'
 'Jakub Herm-Zahlava' 'Carl-Henrik Hansen' 'Marc-Kevin Goellner'
 'Jean-Baptiste Perlant' 'Adrian Menendez-Maceiras' 'Alafia Ayeni'
 'Edoardo Graziani']

In [42]:
null_flags = df_merged1.loc[df_merged1['Player2_flag'].isnull()]
null_names = null_flags['Player2_Name'].unique()
print(null_names)

['Pierre-Hugues Herbert' 'Albert Ramos-Vinolas' 'Inigo Cervantes'
 'Paul-Henri Mathieu' 'Marc-Andrea Huesler' 'Alex de Minaur'
 'Jan-Lennard Struff' 'Thiemo de Bakker' 'Guillermo Garcia-Lopez'
 'Jean-Rene Lisnard' 'Jan-Michael Gambill' 'Cedrik-Marcel Stebe'
 'Mackenzie McDonald' 'Denis Matsukevich' 'Yen-Hsun Lu'
 'Andreas Haider-Maurer' 'Adrian Menendez-Maceiras' 'Soonwoo Kwon'
 'Daniel Gimeno-Traver' 'Fred Gil' 'JC Aragone' 'Bartolome Salva-Vidal'
 'Jonathan Dasnieres de Veigy' 'Jose Hernandez-Fernandez'
 'Roberto Ortega-Olmedo' 'Jean-Claude Scherrer' 'Carl-Henrik Hansen'
 'Fran�ois Musitelli' 'Antoine-Michel Alexeev' 'Patrik Niklas-Salminen'
 "Colin O'Brien" 'Felix Auger-Aliassime' 'Francois-Arthur Vibert'
 'Victor Estrella Burgos' 'Arnau Brugues-Davi' "Massimo Dell'Acqua"
 'Teodor-Dacian Craciun' 'Dimitar Grabul' 'Ante Nakic-Alfirevic'
 'Philipp Davydenko' 'Nuttanon Kadchapanan' 'Woong-Sun Jun'
 'Abdullah Maqdes' 'Juan-Pablo Guzman' 'Pablo Martin-Adalia'
 'Jakub Herm-Zahlava' 'Enric Guaita-Pais' 'Jose Antonio Sanchez-de Luna'
 'Jordi Marse-Vidri' 'Juan-Martin Aranguren' 'Treat Huey'
 'Gabriel Trujillo-Soler' 'Marc Fornell-Mestres' 'Juan Albert Viloca-Puig'
 'Melvyn Op der Heijde' 'Alex Bogomolov Jr.'
 'Daniel-Alejandro Lopez Cassaccia' 'Haythem Abid' 'Mark-Alexander Kepler'
 'Jean-Michel Pequery' 'Hector Ruiz-Cadenas' 'Javier Genaro-Martinez'
 'Tom Kocevar-Desman' 'Thomas Cazes-Carrere' 'Jean-Baptiste Perlant'
 'Jean-Francois Bachelot' 'Jean-Christophe Faurel'
 'Jaume Santo-Valdivieso' 'Javier Garcia-Sintes' 'Marc-Kevin Goellner'
 'Hyung-Taik Lee' 'John van Lottum' 'Oscar Burrieza-Lopez'
 'John-Patrick Smith' 'Sergio Gutierrez-Ferrol' 'Anton Zaitcev'
 'Alafia Ayeni' 'Edoardo Graziani' 'Antoine Cornut-Chauvinc'
 'Johan Tatlot']

In [43]:
# agrupando os df_merged1 pela altura e calculando a média dos pesos por altura
media_pesos_por_altura = df_merged1.groupby('Player1_Height')['Player1_Weight'].mean()

# preenchendo os valores NaN da coluna 'peso' com a média dos pesos correspondentes
df_merged1['Player1_Weight'] = df_merged1['Player1_Weight'].fillna(df_merged1['Player1_Height'].map(media_pesos_por_altura))

In [44]:
# agrupando os df_merged1 pela altura e calculando a média dos pesos por altura
media_pesos_por_altura = df_merged1.groupby('Player2_Height')['Player2_Weight'].mean()

# preenchendo os valores NaN da coluna 'peso' com a média dos pesos correspondentes
df_merged1['Player2_Weight'] = df_merged1['Player2_Weight'].fillna(df_merged1['Player2_Height'].map(media_pesos_por_altura))

In [45]:
df_merged1[['Player1_Weight','Player2_Weight']] = df_merged1[['Player1_Weight','Player2_Weight']].round(0)

In [46]:
df_merged1

,Player1_Name,Player1_Height,Player1_Weight,Player1_turned_pro,Player1_age,Player1_Rank,Tournament,Location,Ground,Prize,...,Player2_age,Player2_Rank,Rank_Diff,birth_year_x,Player2_flag,turned_pro_x,birth_year_y,Player1_flag,turned_pro_y,Start_year
0,Novak Djokovic,188,77.0,8.0,24.0,1,Basel,"Basel, Switzerland",Hard,1308100.0,...,29.0,64,63,1982.0,POL,2002.0,1987.0,SRB,2003.0,NaN
1,Novak Djokovic,188,77.0,8.0,24.0,1,Basel,"Basel, Switzerland",Hard,1308100.0,...,31.0,47,46,1980.0,BEL,1998.0,1987.0,SRB,2003.0,NaN
2,Novak Djokovic,188,77.0,7.0,23.0,3,Basel,"Basel, Switzerland",Hard,1225000.0,...,24.0,32,29,1986.0,SRB,2006.0,1987.0,SRB,2003.0,NaN
3,Novak Djokovic,188,77.0,7.0,23.0,3,Basel,"Basel, Switzerland",Hard,1225000.0,...,23.0,66,63,1987.0,NED,2005.0,1987.0,SRB,2003.0,NaN
4,Novak Djokovic,188,77.0,7.0,23.0,3,Basel,"Basel, Switzerland",Hard,1225000.0,...,22.0,26,23,1988.0,LAT,2004.0,1987.0,SRB,2003.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,Juan Manuel Benitez Chavarriaga,184,79.0,NaN,NaN,646,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,...,23.0,1011,365,1994.0,FRA,NaN,NaN,COL,NaN,NaN
4928,Marvin Moeller,178,69.0,NaN,22.0,614,M25 Trimbach,"Trimbach, Switzerland",Carpet,25000.0,...,NaN,1298,684,NaN,SUI,NaN,1999.0,GER,NaN,NaN
4929,Marvin Moeller,178,69.0,NaN,18.0,1128,Switzerland F5,"Sion, Switzerland",Clay,15000.0,...,24.0,545,583,1993.0,GER,NaN,1999.0,GER,NaN,NaN
4930,Maxence Beauge,183,78.0,NaN,NaN,1325,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,15000.0,...,NaN,941,384,NaN,JPN,NaN,NaN,FRA,NaN,NaN
4931,Nicolas Parizzia,184,79.0,NaN,NaN,1672,M25 Caslano,"Caslano, Switzerland",Clay,25000.0,...,NaN,2048,376,NaN,SUI,NaN,NaN,SUI,NaN,NaN

In [47]:
df_merged1.columns

Index(['Player1_Name', 'Player1_Height', 'Player1_Weight',
       'Player1_turned_pro', 'Player1_age', 'Player1_Rank', 'Tournament',
       'Location', 'Ground', 'Prize', 'GameRound', 'Start_Date', 'End_Date',
       'Tornament_Days', 'Num_Sets', 'TotalPoints', 'GameId', 'Player2_Name',
       'Player2_Height', 'Player2_Weight', 'Player2_turned_pro', 'Player2_age',
       'Player2_Rank', 'Rank_Diff', 'birth_year_x', 'Player2_flag',
       'turned_pro_x', 'birth_year_y', 'Player1_flag', 'turned_pro_y',
       'Start_year'],
      dtype='object')

In [48]:
nova_ordem = ['Player1_Name', 'Player1_Height', 'Player1_Weight',
       'Player1_turned_pro', 'Player1_age', 'Player1_Rank','Player1_flag','Tournament',
       'Location', 'Ground', 'Prize', 'GameRound', 'Start_Date', 'End_Date',
       'Tornament_Days', 'Num_Sets', 'TotalPoints', 'GameId', 'Player2_Name',
       'Player2_Height', 'Player2_Weight', 'Player2_turned_pro', 'Player2_age',
       'Player2_Rank','Player2_flag', 'Rank_Diff'
 
       ]

df_merged1 = df_merged1.reindex(columns=nova_ordem)


df_merged1

,Player1_Name,Player1_Height,Player1_Weight,Player1_turned_pro,Player1_age,Player1_Rank,Player1_flag,Tournament,Location,Ground,...,TotalPoints,GameId,Player2_Name,Player2_Height,Player2_Weight,Player2_turned_pro,Player2_age,Player2_Rank,Player2_flag,Rank_Diff
0,Novak Djokovic,188,77.0,8.0,24.0,1,SRB,Basel,"Basel, Switzerland",Hard,...,15,"Basel_Basel, Switzerland_Hard_1308100.0_Round ...",Lukasz Kubot,191,86.0,9.0,29.0,64,POL,63
1,Novak Djokovic,188,77.0,8.0,24.0,1,SRB,Basel,"Basel, Switzerland",Hard,...,30,"Basel_Basel, Switzerland_Hard_1308100.0_Round ...",Xavier Malisse,185,83.0,13.0,31.0,47,BEL,46
2,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,23,"Basel_Basel, Switzerland_Hard_1225000.0_Semi-F...",Viktor Troicki,193,86.0,4.0,24.0,32,SRB,29
3,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,17,"Basel_Basel, Switzerland_Hard_1225000.0_Quarte...",Robin Haase,191,71.0,5.0,23.0,66,NED,63
4,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,18,"Basel_Basel, Switzerland_Hard_1225000.0_Round ...",Ernests Gulbis,191,88.0,6.0,22.0,26,LAT,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,Juan Manuel Benitez Chavarriaga,184,79.0,NaN,NaN,646,COL,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,...,18,"Switzerland F3_Collonge-Bellerive, Switzerland...",Loic Perret,188,81.0,NaN,23.0,1011,FRA,365
4928,Marvin Moeller,178,69.0,NaN,22.0,614,GER,M25 Trimbach,"Trimbach, Switzerland",Carpet,...,28,"M25 Trimbach_Trimbach, Switzerland_Carpet_2500...",Patrik Hartmeier,184,80.0,NaN,NaN,1298,SUI,684
4929,Marvin Moeller,178,69.0,NaN,18.0,1128,GER,Switzerland F5,"Sion, Switzerland",Clay,...,29,"Switzerland F5_Sion, Switzerland_Clay_15000.0_...",Pascal Meis,180,78.0,NaN,24.0,545,GER,583
4930,Maxence Beauge,183,78.0,NaN,NaN,1325,FRA,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,...,20,"Switzerland F3_Collonge-Bellerive, Switzerland...",Issei Okamura,170,71.0,NaN,NaN,941,JPN,384
4931,Nicolas Parizzia,184,79.0,NaN,NaN,1672,SUI,M25 Caslano,"Caslano, Switzerland",Clay,...,26,"M25 Caslano_Caslano, Switzerland_Clay_25000.0_...",Gian Luca Tanner,191,82.0,NaN,NaN,2048,SUI,376

In [49]:
df_merged1['Num_Sets'].unique()

array([2, 3, 5, 4], dtype=int64)

In [50]:
len(df_merged1)

4932

In [51]:
mask = df_merged1['Player1_turned_pro'] == 0

# Filtra o DataFrame com a máscara booleana
df_merged1_filtrados = df_merged1[mask]

In [52]:
df_merged1_filtrados

,Player1_Name,Player1_Height,Player1_Weight,Player1_turned_pro,Player1_age,Player1_Rank,Player1_flag,Tournament,Location,Ground,...,TotalPoints,GameId,Player2_Name,Player2_Height,Player2_Weight,Player2_turned_pro,Player2_age,Player2_Rank,Player2_flag,Rank_Diff
46,Stefanos Tsitsipas,193,83.0,0.0,18.0,207,GRE,Basel,"Basel, Switzerland",Hard,...,31,"Basel_Basel, Switzerland_Hard_1701320.0_1st Ro...",Rajeev Ram,193,82.0,12.0,32.0,111,USA,96
131,Marin Cilic,198,89.0,0.0,17.0,635,CRO,Geneva,"Geneva, Switzerland",Clay,...,25,"Geneva_Geneva, Switzerland_Clay_37500.0_Round ...",Arnaud Di Pasquale,185,80.0,7.0,26.0,382,FRA,253
136,Karen Khachanov,198,88.0,0.0,17.0,511,RUS,Geneva,"Geneva, Switzerland",Hard,...,31,"Geneva_Geneva, Switzerland_Hard_64000.0_Round ...",Thomas Fabbiano,173,69.0,8.0,24.0,178,ITA,333
137,Karen Khachanov,198,88.0,0.0,17.0,511,RUS,Geneva,"Geneva, Switzerland",Hard,...,18,"Geneva_Geneva, Switzerland_Hard_64000.0_Round ...",Michael Bois,188,81.0,NaN,NaN,599,FRA,88
253,Grigor Dimitrov,191,80.0,0.0,17.0,482,BUL,Basel,"Basel, Switzerland",Hard,...,35,"Basel_Basel, Switzerland_Hard_870000.0_1st Rou...",Jiri Vanek,185,86.0,13.0,30.0,126,CZE,356
539,Henri Laaksonen,185,78.0,0.0,17.0,1392,SUI,Switzerland F3,Switzerland,Carpet,...,34,Switzerland F3_Switzerland_Carpet_10000.0_Roun...,Roman Vogeli,184,80.0,NaN,24.0,620,CZE,772
908,Evgeny Donskoy,185,74.0,0.0,17.0,1001,RUS,Geneva,"Geneva, Switzerland",Clay,...,22,"Geneva_Geneva, Switzerland_Clay_35000.0_Round ...",Ivo Klec,183,79.0,8.0,27.0,222,SVK,779
1559,Janko Tipsarevic,180,80.0,0.0,18.0,405,SRB,Lugano,"Lugano, Switzerland",Clay,...,21,"Lugano_Lugano, Switzerland_Clay_50000.0_Round ...",Markus Hantschk,188,85.0,6.0,25.0,229,GER,176
1823,Matteo Donati,185,74.0,0.0,18.0,426,ITA,Geneva,"Geneva, Switzerland",Hard,...,16,"Geneva_Geneva, Switzerland_Hard_64000.0_3rd Ro...",Laurent Recouderc,184,80.0,NaN,29.0,580,FRA,154
1824,Matteo Donati,185,74.0,0.0,18.0,426,ITA,Geneva,"Geneva, Switzerland",Hard,...,28,"Geneva_Geneva, Switzerland_Hard_64000.0_2nd Ro...",Mikhail Elgin,183,78.0,15.0,32.0,958,RUS,532
1825,Matteo Donati,185,74.0,0.0,18.0,426,ITA,Geneva,"Geneva, Switzerland",Hard,...,18,"Geneva_Geneva, Switzerland_Hard_64000.0_1st Ro...",Marko Osmakcic,193,86.0,NaN,NaN,1001,SUI,575
2027,Vincent Millot,173,75.0,0.0,21.0,593,FRA,Switzerland F1,"Wilen, Switzerland",Carpet,...,26,"Switzerland F1_Wilen, Switzerland_Carpet_10000...",Massimo Dell'Acqua,193,86.0,8.0,28.0,605,NaN,12
2091,Inigo Cervantes,183,78.0,0.0,20.0,277,NaN,Lugano,"Lugano, Switzerland",Clay,...,24,"Lugano_Lugano, Switzerland_Clay_85000.0_2nd Ro...",Max Raditschnigg,184,80.0,NaN,26.0,551,AUT,274
2740,Philipp Petzschner,185,77.0,0.0,17.0,1144,GER,Switzerland F2,Switzerland,Hard,...,22,Switzerland F2_Switzerland_Hard_10000.0_Round ...,Martin Hochstrasser,184,80.0,NaN,NaN,1199,SUI,55
2741,Philipp Petzschner,185,77.0,0.0,17.0,1144,GER,Switzerland F2,Switzerland,Hard,...,17,Switzerland F2_Switzerland_Hard_10000.0_Round ...,Dario Pizzato,201,93.0,NaN,NaN,763,ITA,381
2742,Philipp Petzschner,185,77.0,0.0,17.0,1130,GER,Switzerland F1,Switzerland,Clay,...,17,Switzerland F1_Switzerland_Clay_10000.0_Quarte...,Luben Pampoulov,184,80.0,NaN,NaN,480,AUT,650
2743,Philipp Petzschner,185,77.0,0.0,17.0,1130,GER,Switzerland F1,Switzerland,Clay,...,26,Switzerland F1_Switzerland_Clay_10000.0_Round ...,Massimo Dell'Acqua,193,86.0,2.0,22.0,435,NaN,695
2744,Philipp Petzschner,185,77.0,0.0,17.0,1130,GER,Switzerland F1,Switzerland,Clay,...,14,Switzerland F1_Switzerland_Clay_10000.0_Round ...,Dario Pizzato,201,93.0,NaN,NaN,754,ITA,376
2807,Nicolas Reissig,185,84.0,0.0,20.0,711,AUT,Switzerland F2,Switzerland,Carpet,...,23,Switzerland F2_Switzerland_Carpet_10000.0_Roun...,Dustin Brown,196,78.0,7.0,25.0,442,GER,269
3277,Stephane Bohli,185,82.0,0.0,19.0,768,SUI,Geneva,"Geneva, Switzerland",Clay,...,19,"Geneva_Geneva, Switzerland_Clay_37500.0_Round ...",Melvyn Op der Heijde,180,77.0,5.0,27.0,282,NaN,486
3443,Frank Moser,196,92.0,0.0,25.0,651,GER,Switzerland F1,Switzerland,Clay,...,33,Switzerland F1_Switzerland_Clay_10000.0_Round ...,Alan Mackin,183,79.0,4.0,20.0,485,GBR,166
3630,Kristof Vliegen,193,75.0,0.0,19.0,527,BEL,Switzerland F3,Switzerland,Hard,...,26,Switzerland F3_Switzerland_Hard_10000.0_Quarte...,Michael Berrer,193,100.0,2.0,21.0,517,GER,10
3631,Kristof Vliegen,193,75.0,0.0,19.0,527,BEL,Switzerland F3,Switzerland,Hard,...,20,Switzerland F3_Switzerland_Hard_10000.0_Round ...,Gary Lugassy,184,80.0,NaN,19.0,1001,FRA,474
3632,Kristof Vliegen,193,75.0,0.0,19.0,527,BEL,Switzerland F3,Switzerland,Hard,...,30,Switzerland F3_Switzerland_Hard_10000.0_Round ...,Alan Mackin,183,79.0,4.0,20.0,483,GBR,44
4738,Andy Murray,191,84.0,0.0,18.0,70,GBR,Basel,"Basel, Switzerland",Carpet,...,33,"Basel_Basel, Switzerland_Carpet_975000.0_Round...",Tim Henman,185,77.0,12.0,31.0,28,GBR,42

In [53]:
df_merged1_filtrados[['Player1_age','Player2_age']].mean()

Player1_age    18.280000
Player2_age    25.684211
dtype: float64

In [54]:
age = pd.concat([df_merged1_filtrados['Player1_age'], df_merged1_filtrados['Player2_age']])

In [55]:
age.mean()

21.477272727272727

In [56]:
na_age = df_merged1[df_merged1['Player1_age'].isna()]

In [57]:
na_age['Start_Date']

47     2018-07-23
48     2018-07-23
49     2018-07-23
50     2018-07-23
51     2018-07-23
          ...
4925   2017-08-28
4926   2017-08-14
4927   2017-08-14
4930   2017-08-14
4931   2021-08-23
Name: Start_Date, Length: 771, dtype: datetime64[ns]

In [58]:
df_merged1

,Player1_Name,Player1_Height,Player1_Weight,Player1_turned_pro,Player1_age,Player1_Rank,Player1_flag,Tournament,Location,Ground,...,TotalPoints,GameId,Player2_Name,Player2_Height,Player2_Weight,Player2_turned_pro,Player2_age,Player2_Rank,Player2_flag,Rank_Diff
0,Novak Djokovic,188,77.0,8.0,24.0,1,SRB,Basel,"Basel, Switzerland",Hard,...,15,"Basel_Basel, Switzerland_Hard_1308100.0_Round ...",Lukasz Kubot,191,86.0,9.0,29.0,64,POL,63
1,Novak Djokovic,188,77.0,8.0,24.0,1,SRB,Basel,"Basel, Switzerland",Hard,...,30,"Basel_Basel, Switzerland_Hard_1308100.0_Round ...",Xavier Malisse,185,83.0,13.0,31.0,47,BEL,46
2,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,23,"Basel_Basel, Switzerland_Hard_1225000.0_Semi-F...",Viktor Troicki,193,86.0,4.0,24.0,32,SRB,29
3,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,17,"Basel_Basel, Switzerland_Hard_1225000.0_Quarte...",Robin Haase,191,71.0,5.0,23.0,66,NED,63
4,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,18,"Basel_Basel, Switzerland_Hard_1225000.0_Round ...",Ernests Gulbis,191,88.0,6.0,22.0,26,LAT,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,Juan Manuel Benitez Chavarriaga,184,79.0,NaN,NaN,646,COL,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,...,18,"Switzerland F3_Collonge-Bellerive, Switzerland...",Loic Perret,188,81.0,NaN,23.0,1011,FRA,365
4928,Marvin Moeller,178,69.0,NaN,22.0,614,GER,M25 Trimbach,"Trimbach, Switzerland",Carpet,...,28,"M25 Trimbach_Trimbach, Switzerland_Carpet_2500...",Patrik Hartmeier,184,80.0,NaN,NaN,1298,SUI,684
4929,Marvin Moeller,178,69.0,NaN,18.0,1128,GER,Switzerland F5,"Sion, Switzerland",Clay,...,29,"Switzerland F5_Sion, Switzerland_Clay_15000.0_...",Pascal Meis,180,78.0,NaN,24.0,545,GER,583
4930,Maxence Beauge,183,78.0,NaN,NaN,1325,FRA,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,...,20,"Switzerland F3_Collonge-Bellerive, Switzerland...",Issei Okamura,170,71.0,NaN,NaN,941,JPN,384
4931,Nicolas Parizzia,184,79.0,NaN,NaN,1672,SUI,M25 Caslano,"Caslano, Switzerland",Clay,...,26,"M25 Caslano_Caslano, Switzerland_Clay_25000.0_...",Gian Luca Tanner,191,82.0,NaN,NaN,2048,SUI,376

In [59]:
nan_rows = df_merged1[df_merged1['Player1_age'].isna() | df_merged1['Player2_age'].isna()]
print(nan_rows[['Player1_Name', 'Player1_age', 'Player2_Name', 'Player2_age']])

                         Player1_Name  Player1_age           Player2_Name
19                    Daniil Medvedev         20.0        Daniel Altmaier  \
38                   Alexander Zverev         21.0         Alexei Popyrin
47                  Matteo Berrettini          NaN  Roberto Bautista Agut
48                  Matteo Berrettini          NaN            Jurgen Zopp
49                  Matteo Berrettini          NaN          Andrey Rublev
...                               ...          ...                    ...
4926  Juan Manuel Benitez Chavarriaga          NaN         Nicolas Uryson
4927  Juan Manuel Benitez Chavarriaga          NaN            Loic Perret
4928                   Marvin Moeller         22.0       Patrik Hartmeier
4930                   Maxence Beauge          NaN          Issei Okamura
4931                 Nicolas Parizzia          NaN       Gian Luca Tanner

      Player2_age
19            NaN
38            NaN
47           30.0
48           30.0
49           21.0
...           ...
4926          NaN
4927         23.0
4928          NaN
4930          NaN
4931          NaN

[1414 rows x 4 columns]

In [60]:
df_merged1['Age_Replaced'] = (df_merged1['Player1_age'].isna()) | (df_merged1['Player2_age'].isna())

In [61]:
# obter o ano mínimo de cada jogador
min_year_player1 = df_merged1.groupby('Player1_Name')['Start_Date'].min().dt.year
min_year_player2 = df_merged1.groupby('Player2_Name')['Start_Date'].min().dt.year

# calcular a média de idade de todos os jogadores no dataframe age
mean_age_all = round(age.mean())

# calcular a média de idade de cada jogador no ano mínimo a partir da média do dataframe age
mean_age_player1 = df_merged1.loc[df_merged1['Start_Date'].dt.year.isin(min_year_player1)].groupby('Player1_Name')['Player1_age'].apply(lambda x: x.mean() if x.notnull().any() else mean_age_all)
mean_age_player2 = df_merged1.loc[df_merged1['Start_Date'].dt.year.isin(min_year_player2)].groupby('Player2_Name')['Player2_age'].apply(lambda x: x.mean() if x.notnull().any() else mean_age_all)

# substituir NaN por média de idade
df_merged1['Player1_age'] = df_merged1.apply(lambda x: mean_age_player1[x['Player1_Name']] if pd.isna(x['Player1_age']) else x['Player1_age'], axis=1)
df_merged1['Player2_age'] = df_merged1.apply(lambda x: mean_age_player2[x['Player2_Name']] if pd.isna(x['Player2_age']) else x['Player2_age'], axis=1)

In [62]:
df_merged1

,Player1_Name,Player1_Height,Player1_Weight,Player1_turned_pro,Player1_age,Player1_Rank,Player1_flag,Tournament,Location,Ground,...,GameId,Player2_Name,Player2_Height,Player2_Weight,Player2_turned_pro,Player2_age,Player2_Rank,Player2_flag,Rank_Diff,Age_Replaced
0,Novak Djokovic,188,77.0,8.0,24.0,1,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1308100.0_Round ...",Lukasz Kubot,191,86.0,9.0,29.0,64,POL,63,False
1,Novak Djokovic,188,77.0,8.0,24.0,1,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1308100.0_Round ...",Xavier Malisse,185,83.0,13.0,31.0,47,BEL,46,False
2,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1225000.0_Semi-F...",Viktor Troicki,193,86.0,4.0,24.0,32,SRB,29,False
3,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1225000.0_Quarte...",Robin Haase,191,71.0,5.0,23.0,66,NED,63,False
4,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1225000.0_Round ...",Ernests Gulbis,191,88.0,6.0,22.0,26,LAT,23,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,Juan Manuel Benitez Chavarriaga,184,79.0,NaN,21.0,646,COL,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,...,"Switzerland F3_Collonge-Bellerive, Switzerland...",Loic Perret,188,81.0,NaN,23.0,1011,FRA,365,True
4928,Marvin Moeller,178,69.0,NaN,22.0,614,GER,M25 Trimbach,"Trimbach, Switzerland",Carpet,...,"M25 Trimbach_Trimbach, Switzerland_Carpet_2500...",Patrik Hartmeier,184,80.0,NaN,21.0,1298,SUI,684,True
4929,Marvin Moeller,178,69.0,NaN,18.0,1128,GER,Switzerland F5,"Sion, Switzerland",Clay,...,"Switzerland F5_Sion, Switzerland_Clay_15000.0_...",Pascal Meis,180,78.0,NaN,24.0,545,GER,583,False
4930,Maxence Beauge,183,78.0,NaN,21.0,1325,FRA,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,...,"Switzerland F3_Collonge-Bellerive, Switzerland...",Issei Okamura,170,71.0,NaN,21.0,941,JPN,384,True
4931,Nicolas Parizzia,184,79.0,NaN,21.0,1672,SUI,M25 Caslano,"Caslano, Switzerland",Clay,...,"M25 Caslano_Caslano, Switzerland_Clay_25000.0_...",Gian Luca Tanner,191,82.0,NaN,21.0,2048,SUI,376,True

In [63]:
print(df_merged1[['Player1_Name','Player1_age','Start_Date']])

                         Player1_Name  Player1_age Start_Date
0                      Novak Djokovic         24.0 2011-10-31
1                      Novak Djokovic         24.0 2011-10-31
2                      Novak Djokovic         23.0 2010-11-01
3                      Novak Djokovic         23.0 2010-11-01
4                      Novak Djokovic         23.0 2010-11-01
...                               ...          ...        ...
4927  Juan Manuel Benitez Chavarriaga         21.0 2017-08-14
4928                   Marvin Moeller         22.0 2021-03-08
4929                   Marvin Moeller         18.0 2017-08-28
4930                   Maxence Beauge         21.0 2017-08-14
4931                 Nicolas Parizzia         21.0 2021-08-23

[4932 rows x 3 columns]

In [64]:
df_merged1

,Player1_Name,Player1_Height,Player1_Weight,Player1_turned_pro,Player1_age,Player1_Rank,Player1_flag,Tournament,Location,Ground,...,GameId,Player2_Name,Player2_Height,Player2_Weight,Player2_turned_pro,Player2_age,Player2_Rank,Player2_flag,Rank_Diff,Age_Replaced
0,Novak Djokovic,188,77.0,8.0,24.0,1,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1308100.0_Round ...",Lukasz Kubot,191,86.0,9.0,29.0,64,POL,63,False
1,Novak Djokovic,188,77.0,8.0,24.0,1,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1308100.0_Round ...",Xavier Malisse,185,83.0,13.0,31.0,47,BEL,46,False
2,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1225000.0_Semi-F...",Viktor Troicki,193,86.0,4.0,24.0,32,SRB,29,False
3,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1225000.0_Quarte...",Robin Haase,191,71.0,5.0,23.0,66,NED,63,False
4,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1225000.0_Round ...",Ernests Gulbis,191,88.0,6.0,22.0,26,LAT,23,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,Juan Manuel Benitez Chavarriaga,184,79.0,NaN,21.0,646,COL,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,...,"Switzerland F3_Collonge-Bellerive, Switzerland...",Loic Perret,188,81.0,NaN,23.0,1011,FRA,365,True
4928,Marvin Moeller,178,69.0,NaN,22.0,614,GER,M25 Trimbach,"Trimbach, Switzerland",Carpet,...,"M25 Trimbach_Trimbach, Switzerland_Carpet_2500...",Patrik Hartmeier,184,80.0,NaN,21.0,1298,SUI,684,True
4929,Marvin Moeller,178,69.0,NaN,18.0,1128,GER,Switzerland F5,"Sion, Switzerland",Clay,...,"Switzerland F5_Sion, Switzerland_Clay_15000.0_...",Pascal Meis,180,78.0,NaN,24.0,545,GER,583,False
4930,Maxence Beauge,183,78.0,NaN,21.0,1325,FRA,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,...,"Switzerland F3_Collonge-Bellerive, Switzerland...",Issei Okamura,170,71.0,NaN,21.0,941,JPN,384,True
4931,Nicolas Parizzia,184,79.0,NaN,21.0,1672,SUI,M25 Caslano,"Caslano, Switzerland",Clay,...,"M25 Caslano_Caslano, Switzerland_Clay_25000.0_...",Gian Luca Tanner,191,82.0,NaN,21.0,2048,SUI,376,True

In [65]:
(df_merged1[['Player1_Name','Player1_age','Start_Date']])

                         Player1_Name  Player1_age Start_Date
0                      Novak Djokovic         24.0 2011-10-31
1                      Novak Djokovic         24.0 2011-10-31
2                      Novak Djokovic         23.0 2010-11-01
3                      Novak Djokovic         23.0 2010-11-01
4                      Novak Djokovic         23.0 2010-11-01
...                               ...          ...        ...
4927  Juan Manuel Benitez Chavarriaga         21.0 2017-08-14
4928                   Marvin Moeller         22.0 2021-03-08
4929                   Marvin Moeller         18.0 2017-08-28
4930                   Maxence Beauge         21.0 2017-08-14
4931                 Nicolas Parizzia         21.0 2021-08-23

[4932 rows x 3 columns]

In [66]:
min_age = df_merged1[['Player1_age', 'Player2_age']].min(axis=1)

In [67]:

mask_null_turned_pro = pd.isnull(df_merged1['Player1_turned_pro'])
idx_min_age = df_merged1[(df_merged1['Player1_age'] == min_age) & mask_null_turned_pro].index


df_merged1.loc[idx_min_age, 'Player1_turned_pro'] = 1

mask_null_turned_pro = pd.isnull(df_merged1['Player2_turned_pro'])
idx_min_age = df_merged1[(df_merged1['Player2_age'] == min_age) & mask_null_turned_pro].index


df_merged1.loc[idx_min_age, 'Player2_turned_pro'] = 1

In [68]:
df_merged1

,Player1_Name,Player1_Height,Player1_Weight,Player1_turned_pro,Player1_age,Player1_Rank,Player1_flag,Tournament,Location,Ground,...,GameId,Player2_Name,Player2_Height,Player2_Weight,Player2_turned_pro,Player2_age,Player2_Rank,Player2_flag,Rank_Diff,Age_Replaced
0,Novak Djokovic,188,77.0,8.0,24.0,1,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1308100.0_Round ...",Lukasz Kubot,191,86.0,9.0,29.0,64,POL,63,False
1,Novak Djokovic,188,77.0,8.0,24.0,1,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1308100.0_Round ...",Xavier Malisse,185,83.0,13.0,31.0,47,BEL,46,False
2,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1225000.0_Semi-F...",Viktor Troicki,193,86.0,4.0,24.0,32,SRB,29,False
3,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1225000.0_Quarte...",Robin Haase,191,71.0,5.0,23.0,66,NED,63,False
4,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1225000.0_Round ...",Ernests Gulbis,191,88.0,6.0,22.0,26,LAT,23,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,Juan Manuel Benitez Chavarriaga,184,79.0,1.0,21.0,646,COL,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,...,"Switzerland F3_Collonge-Bellerive, Switzerland...",Loic Perret,188,81.0,NaN,23.0,1011,FRA,365,True
4928,Marvin Moeller,178,69.0,NaN,22.0,614,GER,M25 Trimbach,"Trimbach, Switzerland",Carpet,...,"M25 Trimbach_Trimbach, Switzerland_Carpet_2500...",Patrik Hartmeier,184,80.0,1.0,21.0,1298,SUI,684,True
4929,Marvin Moeller,178,69.0,1.0,18.0,1128,GER,Switzerland F5,"Sion, Switzerland",Clay,...,"Switzerland F5_Sion, Switzerland_Clay_15000.0_...",Pascal Meis,180,78.0,NaN,24.0,545,GER,583,False
4930,Maxence Beauge,183,78.0,1.0,21.0,1325,FRA,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,...,"Switzerland F3_Collonge-Bellerive, Switzerland...",Issei Okamura,170,71.0,1.0,21.0,941,JPN,384,True
4931,Nicolas Parizzia,184,79.0,1.0,21.0,1672,SUI,M25 Caslano,"Caslano, Switzerland",Clay,...,"M25 Caslano_Caslano, Switzerland_Clay_25000.0_...",Gian Luca Tanner,191,82.0,1.0,21.0,2048,SUI,376,True

In [69]:
df

,player_id,player_slug,first_name,last_name,player_url,flag_code,residence,birthplace,birthdate,birth_year,...,birth_day,turned_pro,weight_lbs,weight_kg,height_ft,height_inches,height_cm,handedness,backhand,full_name
0,a002,ricardo-acuna,Ricardo,Acuna,http://www.atpworldtour.com/en/players/ricardo...,CHI,"Jupiter, FL, USA","Santiago, Chile",1958.01.13,1958.0,...,13.0,0.0,150.0,68.0,"5'9""",69.0,175.0,NaN,NaN,Ricardo Acuna
1,a001,sadiq-abdullahi,Sadiq,Abdullahi,http://www.atpworldtour.com/en/players/sadiq-a...,NGR,NaN,NaN,1960.02.02,1960.0,...,2.0,0.0,0.0,0.0,"0'0""",0.0,0.0,NaN,NaN,Sadiq Abdullahi
2,a005,nelson-aerts,Nelson,Aerts,http://www.atpworldtour.com/en/players/nelson-...,BRA,NaN,"Cachoeira Do Sul, Brazil",1963.04.25,1963.0,...,25.0,0.0,165.0,75.0,"6'2""",74.0,188.0,NaN,NaN,Nelson Aerts
3,a004,egan-adams,Egan,Adams,http://www.atpworldtour.com/en/players/egan-ad...,USA,"Palmetto, FL, USA","Miami Beach, FL, USA",1959.06.15,1959.0,...,15.0,0.0,160.0,73.0,"5'10""",70.0,178.0,NaN,NaN,Egan Adams
4,a006,ronald-agenor,Ronald,Agenor,http://www.atpworldtour.com/en/players/ronald-...,USA,"Beverly Hills, California, USA","Rabat, Morocco",1964.11.13,1964.0,...,13.0,1983.0,180.0,82.0,"5'11""",71.0,180.0,NaN,NaN,Ronald Agenor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10907,z435,a-zorab,A.,Zorab,http://www.atpworldtour.com/en/players/a-zorab...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A. Zorab
10908,z437,j-zimmermann,J.,Zimmermann,http://www.atpworldtour.com/en/players/j-zimme...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J. Zimmermann
10909,z436,g-zinn,G.,Zinn,http://www.atpworldtour.com/en/players/g-zinn/...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,G. Zinn
10910,z440,c-zenger,C.,Zenger,http://www.atpworldtour.com/en/players/c-zenge...,GER,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C. Zenger
10911,z442,a-ziffo,A.,Ziffo,http://www.atpworldtour.com/en/players/a-ziffo...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A. Ziffo

In [70]:
df_merged1

,Player1_Name,Player1_Height,Player1_Weight,Player1_turned_pro,Player1_age,Player1_Rank,Player1_flag,Tournament,Location,Ground,...,GameId,Player2_Name,Player2_Height,Player2_Weight,Player2_turned_pro,Player2_age,Player2_Rank,Player2_flag,Rank_Diff,Age_Replaced
0,Novak Djokovic,188,77.0,8.0,24.0,1,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1308100.0_Round ...",Lukasz Kubot,191,86.0,9.0,29.0,64,POL,63,False
1,Novak Djokovic,188,77.0,8.0,24.0,1,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1308100.0_Round ...",Xavier Malisse,185,83.0,13.0,31.0,47,BEL,46,False
2,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1225000.0_Semi-F...",Viktor Troicki,193,86.0,4.0,24.0,32,SRB,29,False
3,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1225000.0_Quarte...",Robin Haase,191,71.0,5.0,23.0,66,NED,63,False
4,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,"Basel_Basel, Switzerland_Hard_1225000.0_Round ...",Ernests Gulbis,191,88.0,6.0,22.0,26,LAT,23,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,Juan Manuel Benitez Chavarriaga,184,79.0,1.0,21.0,646,COL,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,...,"Switzerland F3_Collonge-Bellerive, Switzerland...",Loic Perret,188,81.0,NaN,23.0,1011,FRA,365,True
4928,Marvin Moeller,178,69.0,NaN,22.0,614,GER,M25 Trimbach,"Trimbach, Switzerland",Carpet,...,"M25 Trimbach_Trimbach, Switzerland_Carpet_2500...",Patrik Hartmeier,184,80.0,1.0,21.0,1298,SUI,684,True
4929,Marvin Moeller,178,69.0,1.0,18.0,1128,GER,Switzerland F5,"Sion, Switzerland",Clay,...,"Switzerland F5_Sion, Switzerland_Clay_15000.0_...",Pascal Meis,180,78.0,NaN,24.0,545,GER,583,False
4930,Maxence Beauge,183,78.0,1.0,21.0,1325,FRA,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,...,"Switzerland F3_Collonge-Bellerive, Switzerland...",Issei Okamura,170,71.0,1.0,21.0,941,JPN,384,True
4931,Nicolas Parizzia,184,79.0,1.0,21.0,1672,SUI,M25 Caslano,"Caslano, Switzerland",Clay,...,"M25 Caslano_Caslano, Switzerland_Clay_25000.0_...",Gian Luca Tanner,191,82.0,1.0,21.0,2048,SUI,376,True

In [71]:
df_merged1['Player1_turned_pro'].isna().any()

True

In [72]:
df_merged1['Player1_turned_pro'].fillna(0, axis=0, inplace=True)
df_merged1['Player2_turned_pro'].fillna(0, axis=0, inplace=True)

In [73]:
# Dicionário para armazenar a idade do jogador quando virou profissional
turned_pro_dict = {}

# Iterar sobre as linhas com turned_pro = 1
for idx, row in df_merged1[df_merged1['Player1_turned_pro'] == 1].iterrows():
    player_name = row['Player1_Name']
    player_age = row['Player1_age']
    turned_pro_dict[player_name] = player_age

# Iterar sobre as linhas com turned_pro = 0
for idx, row in df_merged1[df_merged1['Player1_turned_pro'] == 0].iterrows():
    player_name = row['Player1_Name']
    player_age = row['Player1_age']
    if player_name in turned_pro_dict:
        age_diff = player_age - turned_pro_dict[player_name] + 1
        df_merged1.at[idx, 'Player1_turned_pro'] = age_diff

# Dicionário para armazenar a idade do jogador quando virou profissional
turned_pro_dict2 = {}

# Iterar sobre as linhas com turned_pro = 1
for idx, row in df_merged1[df_merged1['Player2_turned_pro'] == 1].iterrows():
    player_name = row['Player2_Name']
    player_age = row['Player2_age']
    turned_pro_dict[player_name] = player_age

# Iterar sobre as linhas com turned_pro = 0
for idx, row in df_merged1[df_merged1['Player2_turned_pro'] == 0].iterrows():
    player_name = row['Player2_Name']
    player_age = row['Player2_age']
    if player_name in turned_pro_dict:
        age_diff = player_age - turned_pro_dict[player_name] + 1
        df_merged1.at[idx, 'Player2_turned_pro'] = age_diff

In [74]:
df_merged1['Player1_turned_pro'].isna().any()

False

In [75]:
df_merged1['Player2_turned_pro'].isna().any()

False

In [79]:
df_merged1 = df_merged1.drop(['Age_Replaced'],axis=1)

In [80]:
df_merged1

,Player1_Name,Player1_Height,Player1_Weight,Player1_turned_pro,Player1_age,Player1_Rank,Player1_flag,Tournament,Location,Ground,...,TotalPoints,GameId,Player2_Name,Player2_Height,Player2_Weight,Player2_turned_pro,Player2_age,Player2_Rank,Player2_flag,Rank_Diff
0,Novak Djokovic,188,77.0,8.0,24.0,1,SRB,Basel,"Basel, Switzerland",Hard,...,15,"Basel_Basel, Switzerland_Hard_1308100.0_Round ...",Lukasz Kubot,191,86.0,9.0,29.0,64,POL,63
1,Novak Djokovic,188,77.0,8.0,24.0,1,SRB,Basel,"Basel, Switzerland",Hard,...,30,"Basel_Basel, Switzerland_Hard_1308100.0_Round ...",Xavier Malisse,185,83.0,13.0,31.0,47,BEL,46
2,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,23,"Basel_Basel, Switzerland_Hard_1225000.0_Semi-F...",Viktor Troicki,193,86.0,4.0,24.0,32,SRB,29
3,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,17,"Basel_Basel, Switzerland_Hard_1225000.0_Quarte...",Robin Haase,191,71.0,5.0,23.0,66,NED,63
4,Novak Djokovic,188,77.0,7.0,23.0,3,SRB,Basel,"Basel, Switzerland",Hard,...,18,"Basel_Basel, Switzerland_Hard_1225000.0_Round ...",Ernests Gulbis,191,88.0,6.0,22.0,26,LAT,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927,Juan Manuel Benitez Chavarriaga,184,79.0,1.0,21.0,646,COL,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,...,18,"Switzerland F3_Collonge-Bellerive, Switzerland...",Loic Perret,188,81.0,6.0,23.0,1011,FRA,365
4928,Marvin Moeller,178,69.0,5.0,22.0,614,GER,M25 Trimbach,"Trimbach, Switzerland",Carpet,...,28,"M25 Trimbach_Trimbach, Switzerland_Carpet_2500...",Patrik Hartmeier,184,80.0,1.0,21.0,1298,SUI,684
4929,Marvin Moeller,178,69.0,1.0,18.0,1128,GER,Switzerland F5,"Sion, Switzerland",Clay,...,29,"Switzerland F5_Sion, Switzerland_Clay_15000.0_...",Pascal Meis,180,78.0,2.0,24.0,545,GER,583
4930,Maxence Beauge,183,78.0,1.0,21.0,1325,FRA,Switzerland F3,"Collonge-Bellerive, Switzerland",Clay,...,20,"Switzerland F3_Collonge-Bellerive, Switzerland...",Issei Okamura,170,71.0,1.0,21.0,941,JPN,384
4931,Nicolas Parizzia,184,79.0,1.0,21.0,1672,SUI,M25 Caslano,"Caslano, Switzerland",Clay,...,26,"M25 Caslano_Caslano, Switzerland_Clay_25000.0_...",Gian Luca Tanner,191,82.0,1.0,21.0,2048,SUI,376

## WEB SCRAPING

In [ ]:
from lxml import etree
import requests
from bs4 import BeautifulSoup
import pandas as pd

def extract_element(url):
    headers = {'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 OPR/98.0.0.0"}
    site = requests.get(url=url, headers=headers)
    soup = BeautifulSoup(site.text, "html.parser")
    dom = etree.HTML(str(soup))
    element = dom.xpath('//div[@class="player-flag-code"]/text()')
    return element[0] if element else ''

# carrega o dataframe com os links
df_links = pd.read_csv('link.csv')
# extrai o elemento de cada URL e adiciona uma nova coluna no dataframe
df_links['player-flag-code'] = df_links['LinkPlayer'].apply(extract_element)

# mostra o dataframe resultante
print(df_links)

In [1]:
import time

start_time = time.time()


from lxml import etree
import requests
from bs4 import BeautifulSoup
import pandas as pd

def extract_element(url):
    headers = {'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 OPR/98.0.0.0"}
    site = requests.get(url=url, headers=headers)
    soup = BeautifulSoup(site.text, "html.parser")
    dom = etree.HTML(str(soup))
    element = dom.xpath('//div[@class="player-flag-code"]/text()')
    return element[0] if element else ''

def extract_name(url):
    headers = {'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 OPR/98.0.0.0"}
    site = requests.get(url=url, headers=headers)
    soup = BeautifulSoup(site.text, "html.parser")
    name = soup.find('meta', {'property': 'pageTransitionTitle'})['content']
    return name



# carrega o dataframe com os links
df_links = pd.read_csv('link.csv')

# extrai o elemento de cada URL e adiciona uma nova coluna no dataframe
df_links['player-flag-code'] = df_links['LinkPlayer'].apply(extract_element)
# adiciona uma nova coluna com o nome do jogador
df_links['player-name'] = df_links['LinkPlayer'].apply(extract_name)
# mostra o dataframe resultante
print(df_links)

end_time = time.time()
print("Tempo de execução: ", end_time - start_time, " segundos")

                                          LinkPlayer player-flag-code
0  https://www.atptour.com/en/players/novak-djoko...              SRB  \
1  https://www.atptour.com/en/players/daniil-medv...
2  https://www.atptour.com/en/players/rafael-nada...              ESP
3  https://www.atptour.com/en/players/alexander-z...              GER
4  https://www.atptour.com/en/players/stefanos-ts...              GRE
5  https://www.atptour.com/en/players/matteo-berr...              ITA
6  https://www.atptour.com/en/players/andrey-rubl...
7  https://www.atptour.com/en/players/casper-ruud...              NOR

          player-name
0      Novak Djokovic
1     Daniil Medvedev
2        Rafael Nadal
3    Alexander Zverev
4  Stefanos Tsitsipas
5   Matteo Berrettini
6       Andrey Rublev
7         Casper Ruud
Tempo de execução:  71.41578388214111  segundos

In [ ]:
from lxml import etree
import requests
from bs4 import BeautifulSoup
import pandas as pd

def extract_element(url):
    headers = {'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 OPR/98.0.0.0"}
    site = requests.get(url=url, headers=headers)
    soup = BeautifulSoup(site.text, "html.parser")
    title_element = soup.find("h1", class_="page-title")
    name = title_element.text if title_element else ''
    dom = etree.HTML(str(soup))
    flag_element = dom.xpath('//div[@class="player-flag-code"]/text()')
    flag = flag_element[0] if flag_element else ''
    return name, flag

# carrega o dataframe com os links
df_links = pd.read_csv('link.csv')

# extrai o nome e o código do país de cada URL e adiciona novas colunas no dataframe
df_links[['player-name', 'player-flag-code']] = df_links['LinkPlayer'].apply(extract_element).apply(pd.Series)

# mostra o dataframe resultante
print(df_links)

In [81]:
df_merged1.columns

Index(['Player1_Name', 'Player1_Height', 'Player1_Weight',
       'Player1_turned_pro', 'Player1_age', 'Player1_Rank', 'Player1_flag',
       'Tournament', 'Location', 'Ground', 'Prize', 'GameRound', 'Start_Date',
       'End_Date', 'Tornament_Days', 'Num_Sets', 'TotalPoints', 'GameId',
       'Player2_Name', 'Player2_Height', 'Player2_Weight',
       'Player2_turned_pro', 'Player2_age', 'Player2_Rank', 'Player2_flag',
       'Rank_Diff'],
      dtype='object')